### ISSUE TITLE
Airplay increases volume to maximum

### ISSUE THREAD

**Issue by hifiberry** [hifiberry/hifiberry-os#10]
When using Airplay, it can happen that the volume control increases automatically.
It is not yet clear, when this happens.

**Comment by hifiberry** [comment]
Seems to be a bug in the Beocreate web interface.

**Comment by hifiberry** [comment]
This has been fixed with a new Beocreate release

**Comment by danbee** [comment]
I know this is closed, but I'm experiencing this now with the latest version of HifiBerryOS on a Raspberry Pi 3. Sometimes it jumps momentarily and back down again. Sometimes it jumps and doesn't reset until I tweak the volume slider.

**Comment by hifiberry** [comment]
You problem has probably nothing to do with this. Try disabling Spotify and check if this still happens. If you have configured a username/password for Spotify, remove this.

**Comment by danbee** [comment]
Thank you for your reply. I found the other thread and disabling Spotify does indeed seem to solve this!
