### ISSUE TITLE
HiFiBerry OS unstable with Pi2 and Digi+

### ISSUE THREAD

**Issue by asx77** [hifiberry/hifiberry-os#102]
Hi,
I've installed hifiberryOS version for Pi2 and just on the initial set-up i keep losing connection and have to wait for connection to re-establish. Has anyone found the same happening? How did you fix?

Thanks
Alex

**Comment by hifiberry** [comment]
On initial setup, the system has to reboot 2 times to detect and configure the hardware. That's normal.

**Comment by hifiberry** [comment]
BTW: If you want to get feedback from users, it's better to post in the HiFiBerry community area:
https://support.hifiberry.com/hc/en-us/community/topics/200402012-Software
