### ISSUE TITLE
WiFi PowerSave disconnects RaspberryPi

### ISSUE THREAD

**Issue by PatrickDrewsES** [hifiberry/hifiberry-os#106]
**Describe the bug**
WiFi is disconnected regularly. I assume its the power-saving feature of the pi 4. However, PowerSave should be turned off by default.
/etc/network/interfaces.bak do not include a command for turning power save off.

**HiFiBerryOS version**
20200527

**HiFiBerry sound card**
DAC+ pro

**To Reproduce**
do nothing (idle leads to power save)

**Expected behavior**
should always be online

**Screenshots**
none

**Browser (if applicable)**
not applicable

**Additional context**
infrastructure is a fritz!box network with mesh repeater

**Comment by PatrickDrewsES** [comment]
was easy since iwconfig is included:

`iwconfig wlan0 power off`

sorry for bothering you, guys.

**Comment by fredrike** [comment]
@PatrickDrewsES how did you put `iwconfig wlan0 power off` to run after a reboot?
