### ISSUE TITLE
Open source Sonos

### ISSUE THREAD

**Issue by ibex-are-goats** [hifiberry/hifiberry-os#108]
Hello! I've tried some of the Raspberry Pi music operating systems available and they seem very primitive. I understand that Linux has the ability to have multiple synchronized music playback clients like Sonos does. Will Hifiberry OS be the distro that gets it right?

**Comment by hifiberry** [comment]
HiFiBerryOS supports several clients that can be used for this:
- Roon
- Squeezelite
- Snapcast

All require an central control server that is NOT part of HiFiBerryOS. 

Feel free to test what works best for you. 
BTW: I know a lot of similar disributions and I would not call most of them "primitive". There's a lot of good software around.
