### ISSUE TITLE
wifi has turned itself on and created the setup access point

### ISSUE THREAD

**Issue by Farcus2000** [hifiberry/hifiberry-os#109]
**Describe the bug**
wifi has turned itself on and created the setup access point

**HiFiBerryOS version**
20200527

**HiFiBerry sound card**
DAC+ Pro

**To Reproduce**
Something happenes about every 7 days

**Expected behavior**
With wifi disabled and setup complete I do not expect the setup wifi basestation to spring back into life.
[hifiberry-debug-2.zip](https://github.com/hifiberry/hifiberry-os/files/4813065/hifiberry-debug-2.zip)

**Comment by hifiberry** [comment]
Thanks for reporting this. WiFi AP should only be enabled if no network is detected after a reboot. Is it possible that there was a power outage when this happened?

**Comment by Farcus2000** [comment]
Agree a possible cause. No outage today or last week with same symptom.

**Comment by hifiberry** [comment]
Unfortunately I can't say why this happend. Try the latest release and make sure WiFi is deactived in the network settings.

**Comment by Farcus2000** [comment]
Update installed overnight without a hitch. The access point activated again Saturday, about a week apart. 

All the configuration settings retained and confirm wifi disabled. Thank you.

**Comment by hifiberry** [comment]
Did this happen again with the latest release?

**Comment by Farcus2000** [comment]
Thank you for checking back. 

Afraid so. Most recent was overnight 15th July no power or internet outage.

Last week 8th was not clear as there was an interim OS update as well as a maintenance outage on my ISP and the WAP activated. I didn't flag it as the ISP being down was a new dimension.

Loving the sound, particularly notice voice. Roon trial underway and works really well.

Thanks again.

Mal

**Comment by hifiberry** [comment]
Ok, in the next release, we'll add a way to fully disable this. You can create a file "noap" on the FAT partition of the SD card (either on your PC or on the system in /boot). If this file exists, the access point will never be started.

https://github.com/hifiberry/hifiberry-os/commit/97c4e801710209e9acba07f07ef9b813342e05bc

**Comment by MattHardwick34** [comment]
Trying to create noap file results in a message about read only file system. Why isn't there an option to disable this feature though the configuration?

**Comment by hifiberry** [comment]
You need to remount the file system read-write

mount -o remount,rw /boot

We won't add UI configuration options for every feature - we don't want to end up like other distributions with hundreds of settings in the UI.

**Comment by MattHardwick34** [comment]
OK that worked thanks - we'll see how things go after a week or two!
And that makes sense but shame we can't get to the bottom of why it's randomly starting!

**Comment by EpicLPer** [comment]
> Ok, in the next release, we'll add a way to fully disable this. You can create a file "noap" on the FAT partition of the SD card (either on your PC or on the system in /boot). If this file exists, the access point will never be started.
> 
> [97c4e80](https://github.com/hifiberry/hifiberry-os/commit/97c4e801710209e9acba07f07ef9b813342e05bc)

I just want to throw in my few cents and say that this is a really bad decision... for over a year now I had various network problems and never could quite figure out why, until I ran a Wireshark trace today and finally figured out that HiFiBerryOS throws in random DHCP offers...
I've had servers on my network go down because it assigned IPs that were not available in the DHCP range, had mobile phones ask for guest logins that didn't exist due to this and it caused quite a few awkward moments at home due to this...

It'd be great to at least mention in the setup guide that this could be a problem and that this option exists, so others with less knowledge don't suddenly have to debug this on their own.

**Comment by tompeel** [comment]
I agree, this has taken me a long time to get to the root of quite a few problems. Its an incredibly dificult thing to track down especially for people who dont know how to use a complicated tool like Wireshark (I do) I spent over 18 months thinking is was an issue with a Unifi certificate as all the phones would get DHCP from this.
Can it not jsut be hard disabled unless you enable AP mode... i never used AP mode and didnt even know it was a thing?! No UI option for AP mode ether i dont think but somewhere this needs shutting down.
