### ISSUE TITLE
Spotify playback not showing in web interface

### ISSUE THREAD

**Issue by danvincent** [hifiberry/hifiberry-os#114]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**

**HiFiBerryOS version**
20200701 and 20200621

**HiFiBerry sound card**
Post the exact type, e.g. DAC+ Pro instead of "DAC+".
DAC+

**To Reproduce**
Play a track on Spotify and transfer playback to the HiFiBerry

**Expected behavior**
Sources should display track details and artwork (where available)

**Screenshots**
![Screenshot_20200702-204700](https://user-images.githubusercontent.com/2820964/86403268-461aab00-bca5-11ea-9dc0-ef33b611978e.png)

**Browser (if applicable)**
 - OS: Android 10
 - Browser: Chrome

**Additional context**
Appears to have started in 20200621

**Comment by hifiberry** [comment]
Thanks for reporting this. This is really a new bug that has been introduced with the work on the local music library. Bugfix will be included in the next release.

**Comment by hifiberry** [comment]
https://github.com/hifiberry/audiocontrol2/commit/0cbe8f3c273f023227f4ee8af92862891a90165a

**Comment by hifiberry** [comment]
Can you check the latest version? This should be fixed already.

**Comment by danvincent** [comment]
Yep fixed in the last version ✅

**Comment by danvincent** [comment]
✅✅✅
