### ISSUE TITLE
Support for rating, sticker_file, sqlite

### ISSUE THREAD

**Issue by michuno** [hifiberry/hifiberry-os#116]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete feature requests will be closed.
You should remove this comment before posting the feature request.

**Is your feature request related to a problem? Please describe.**
I'm running HifiBerryOS version 20200527 on Raspberry Pi 3 Model B.
When I enable sticker_file in the mpd.conf I get an error message ("Cannot store ratings, as the 'sticker' MPD command is not supported.") because sqlite not supported I guess.

**Describe the solution you'd like**
mpd shall support the feature of sticker_file, most importantly **Ratings**

**Describe alternatives you've considered**
Debian based mpd binaries support sqlite and sticker_file

**Additional context**
Error message I get: Cannot store ratings, as the 'sticker' MPD command is not supported

**Comment by hifiberry** [comment]
mpd is integrated with sqlite support already. I tested this here and it's working fine:

sticker_file "/library/mpd-sticker.db"

mpc sticker 1/test.flac set rating 1
mpc sticker 1/test.flac get rating
rating=1

You should check your configuration.
