### ISSUE TITLE
Inclusion of CMUS (or other CLI driven player)

### ISSUE THREAD

**Issue by Dannyzen** [hifiberry/hifiberry-os#130]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete feature requests will be closed.
You should remove this comment before posting the feature request.

**Is your feature request related to a problem? Please describe.**
I'm interested in using [CMUS ](https://cmus.github.io/) with Hifiberry-os
**Describe the solution you'd like**

cmus is a small, fast and powerful console music player for Unix-like operating systems. It is compelling as it provides a sshable interface for music to be played through, a feature not currently provided by hifiberry-os

**Describe alternatives you've considered**

https://www.tecmint.com/command-line-music-players-for-linux/ lists 5, CMUS is chosen for its stability and flexibility

**Additional context**

CMUS also provides 'folder based' play functionality for those of us who have files that lack id3 tags or traceable fingerprints

**Comment by hifiberry** [comment]
HiFiBerryOS isn't designed to be used from command line or via SSH. Therefore, we won't integrate any players like this. For something like this, I recommend not to use HiFiBerryOS at all. A plain Raspbian might be the better choice for this.
If you need some minimal scripting, you can do this already with mpd which is included.

**Comment by Dannyzen** [comment]
Thanks!
