### ISSUE TITLE
RPI 4B 8GB dacplus not working

### ISSUE THREAD

**Issue by mtausk** [hifiberry/hifiberry-os#137]
**Describe the bug**

Hi,

I moved my hifiberry dacplus from RPI 3B to brand new RPI 4B 8GB and it does not work.

- first I tried to use the same SD card (ubuntu mate)
- then I tried new image of raspbian (raspberry OS) with new linux driver
- then I reverted core to 4.19.118-v7l

but nothing helped.

Current status:

root@raspberrypi:~# egrep -v '^(#|$)' /boot/config.txt
dtoverlay=hifiberry-dacplus
dtdebug=1
[pi4]
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
[all]
gpu_mem=256

root@raspberrypi:~# aplay -l
aplay: device_list:272: no soundcards found...
root@raspberrypi:~# uname -a
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

DMESG:
[    0.000000] Linux version 4.19.118-v7l+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1311 SMP Mon Apr 27 14:26:42 BST 2020
[    0.000000] CPU: ARMv7 Processor [410fd083] revision 3 (ARMv7), cr=30c5383d
[    0.000000] OF: fdt: Machine model: Raspberry Pi 4 Model B Rev 1.4
[    0.000000] cma: Reserved 256 MiB at 0x000000001ec00000
[    0.000000] Memory: 7710292K/8060928K available (8192K kernel code, 690K rwdata, 2420K rodata, 2048K init, 860K bss, 88492K reserved, 262144K cma-reserved, 7274496K highmem)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xf0800000 - 0xff800000   ( 240 MB)
                   lowmem  : 0xc0000000 - 0xf0000000   ( 768 MB)
                   pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
                   modules : 0xbf000000 - 0xbfe00000   (  14 MB)
                     .text : 0x(ptrval) - 0x(ptrval)   (10208 kB)
                     .init : 0x(ptrval) - 0x(ptrval)   (2048 kB)
                     .data : 0x(ptrval) - 0x(ptrval)   ( 691 kB)
                      .bss : 0x(ptrval) - 0x(ptrval)   ( 861 kB)
[    0.050044] raspberrypi-firmware soc:firmware: Attached to firmware from 2020-05-11 18:59, variant start
[    0.060057] raspberrypi-firmware soc:firmware: Firmware hash is 21bfdeee3a6ea823e2113b983390acd1eec8edfb
[    0.103051] bcm2835-dma fe007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
[    0.226076] hw perfevents: enabled with armv7_cortex_a15 PMU driver, 7 counters available
[    0.277695] brcm-pcie fd500000.pcie: dmabounce: initialised - 32768 kB, threshold 0x00000000c0000000
[    0.277715] brcm-pcie fd500000.pcie: could not get clock
[    0.277780] brcm-pcie fd500000.pcie: host bridge /scb/pcie@7d500000 ranges:
[    0.277820] brcm-pcie fd500000.pcie:   MEM 0x600000000..0x603ffffff -> 0xf8000000
[    0.358556] brcm-pcie fd500000.pcie: link up, 5.0 Gbps x1 (!SSC)
[    0.358851] brcm-pcie fd500000.pcie: PCI host bridge to bus 0000:00
[    0.545423] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    0.545987] brcmstb_thermal fd5d2200.thermal: registered AVS TMON of-sensor driver
[    4.136371] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CPU DAI (null) not registered - will retry
[    4.137049] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    4.263035] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    4.562499] [drm] Initialized v3d 1.0.0 20180419 for fec00000.v3d on minor 0
[    4.567848] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    4.631277] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    4.649079] vc4-drm soc:gpu: bound fe600000.firmwarekms (ops vc4_fkms_ops [vc4])
[    4.649098] checking generic (3e330000 8ca000) vs hw (0 ffffffffffffffff)
[    4.649108] fb: switching to vc4drmfb from simple
[    4.649372] Console: switching to colour dummy device 80x30
[    4.654185] [drm] Initialized vc4 0.0.0 20140616 for soc:gpu on minor 1
[    4.654199] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    4.654209] [drm] No driver support for vblank timestamp query.
[    4.654218] [drm] Setting vblank_disable_immediate to false because get_vblank_timestamp == NULL
[    4.667876] Console: switching to colour frame buffer device 240x75
[    4.667917] vc4-drm soc:gpu: fb0: DRM emulated frame buffer device
[    4.688842] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    4.719927] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    4.732690] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    4.783303] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    4.789658] brcmfmac: F1 signature read @0x18000000=0x15264345
[    4.801475] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    4.802275] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    4.804172] usbcore: registered new interface driver brcmfmac
[    5.033274] pcm512x 1-004d: Linked as a consumer to regulator.1
[    5.039005] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    5.051166] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Mar 23 2020 02:19:54 version 7.45.206 (r725000 CY) FWID 01-88ee44ea
[    5.223537] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[    5.226034] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[    5.226052] [vc_sm_connected_init]: start
[    5.235201] rpivid-mem feb00000.hevc-decoder: rpivid-hevcmem initialised: Registers at 0xfeb00000 length 0x0000ffff
[    5.235591] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    5.235756] [vc_sm_connected_init]: installed successfully
[    5.236147] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    5.240994] media: Linux media interface: v0.10
[    5.243135] rpivid-mem feb10000.rpivid-local-intc: rpivid-intcmem initialised: Registers at 0xfeb10000 length 0x00000fff
[    5.243529] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    5.244376] rpivid-mem feb20000.h264-decoder: rpivid-h264mem initialised: Registers at 0xfeb20000 length 0x0000ffff
[    5.244760] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    5.247037] rpivid-mem feb30000.vp9-decoder: rpivid-vp9mem initialised: Registers at 0xfeb30000 length 0x0000ffff
[    5.247426] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    5.274639] videodev: Linux video capture interface: v2.00
[    5.326697] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    5.326705] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    5.339934] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[    5.349234] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[    5.352727] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[    5.352766] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[    5.367847] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[    5.367885] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[    5.376329] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[    5.376362] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[    5.376926] snd-rpi-hifiberry-dacplus soc:sound: ASoC: CODEC DAI pcm512x-hifi not registered - will retry
[    5.544693] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    5.550935] sd 1:0:0:0: Attached scsi generic sg1 type 0

root@raspberrypi:~# sudo vcdbg log msg 2>&1| grep dacplus
007163.367: brfs: File read: /mfs/sd/overlays/hifiberry-dacplus.dtbo
007268.002: Loaded overlay 'hifiberry-dacplus'

dtc -I fs /proc/device-tree
                dacpro_osc {
                        compatible = "hifiberry,dacpro-clk";
                        #clock-cells = < 0x00 >;
                        phandle = < 0xca >;
                };
                sound {
                        compatible = "hifiberry,hifiberry-dacplus";
                        i2s-controller = < 0x25 >;
                        status = "okay";
                        phandle = < 0xbe >;
                };

root@raspberrypi:~# lsmod | egrep 'snd|dacplus'
snd_soc_pcm512x_i2c    16384  0
snd_soc_pcm512x        32768  1 snd_soc_pcm512x_i2c
snd_soc_hifiberry_dacplus    16384  0
snd_soc_bcm2835_i2s    20480  0
snd_soc_core          192512  4 snd_soc_pcm512x,vc4,snd_soc_hifiberry_dacplus,snd_soc_bcm2835_i2s
snd_compress           20480  1 snd_soc_core
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_pcm               102400  6 snd_soc_pcm512x,vc4,snd_pcm_dmaengine,snd_soc_hifiberry_dacplus,snd_soc_bcm2835_i2s,snd_soc_core
snd_timer              32768  1 snd_pcm
snd                    73728  5 snd_compress,snd_soc_pcm512x,snd_timer,snd_soc_core,snd_pcm

**HiFiBerryOS version**
This is Raspberry OS / Raspbian. The newest one.
But I tried on ubuntu mate (whare the same dacplus worked on rpi 3b) and I tried to downgrade the rpi to newest 4.19 branch (rpi-update e1050e94821a70b2e4c72b318d6c6c968552e9a2)

**HiFiBerry sound card**
DAC+

**To Reproduce**
root@raspberrypi:~# aplay -l
aplay: device_list:272: no soundcards found...

**Expected behavior**
I expect to find soundcards.

**Screenshots**
N/A

**Browser (if applicable)**
root@raspberrypi:~# lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Additional context**
Thanks.

**Comment by hifiberry** [comment]
You're not using HiFiBerryOS, but Raspbian. This isn't a HiFiBerryOS bug. Please use the HiFiBerry support forum for general questions.
