### ISSUE TITLE
Touchscreen not working

### ISSUE THREAD

**Issue by lucasso72** [hifiberry/hifiberry-os#141]
**Describe the bug**
After update to latest version  the touchscreen of the external display is not working anymore, it's stuck in the "now playing" screen tho it's being updated with current song.

**HiFiBerryOS version**
20200908

**HiFiBerry sound card**
CURRENT_PIMODEL=3B
CURRENT_MIXER_CONTROL="Digital"
CURRENT_CARD="DAC+ Pro"
CURRENT_HW="card 0"
CURRENT_HW_SHORT=0
CURRENT_SYSNAME="HiFiBerry"
CURRENT_PLAYERS=""
CURRENT_HATINFO=""
CURRENT_FEATURES="pi pi3orlater arm7 localui"
PIVERSION=3

**To Reproduce**
touching any part of the screen there's no reaction whatsoever 

**Expected behavior**
See "Describe the bug" section.

**Screenshots**
See "Describe the bug" section.

**Browser (if applicable)**
N/A

**Additional context**

**Comment by lucasso72** [comment]
anyone to acknowledge this?

**Comment by hifiberry** [comment]
Can't see this here. However, I don't have a touchscreen to test with.

**Comment by lucasso72** [comment]
anything I can provide to help troubleshoot?

**Comment by lucasso72** [comment]
On Raspberrypi.org I found this command the check the touchscreen has been detected:

` dmesg | grep -i ft5406`

and in my case it doesn't return what's expected. I'm trying to understand if it's an hw issue but it's strange because it was working until the moment I upgraded to latest hifiberry release. I just tried to go back to previous version and the problem remain...

**Comment by lucasso72** [comment]
Guys I checked by installing Raspberry pi OS and the touch screen is working, so it's not an hw issue. Also is strange that reverting the Hifiberry back to the previous installed version, keep having the issue.

**Comment by hifiberry** [comment]
Might be a problem with the firmware on the latest version:
https://support.hifiberry.com/hc/en-us/community/posts/360012803457

**Comment by lucasso72** [comment]
Any plan to release a build that fixes this issue? tks.

**Comment by hifiberry** [comment]
This will be fixed in the next release

**Comment by hifiberry** [comment]
@lucasso72 I think this is fixed now - correct?

**Comment by lucasso72** [comment]
Correct! thanks.
