### ISSUE TITLE
Version number cannot be copied from the about screen

### ISSUE THREAD

**Issue by Bertware** [hifiberry/hifiberry-os#145]
**Describe the bug**
When you try to select the version number on the about screen, it changes to some other information. You cannot select and copy the version number. This is a bit annoying given that it is required in bug reports.

**HiFiBerryOS version**
20200908

**Expected behavior**
The version number can be selected and copied. Alternatively, some "copy version information" button could copy all relevant version numbers to the clipboard, so they can easily be pasted in bug reports. A "report a bug" link might be useful in order to guide users here.

**Browser (if applicable)**
 - OS: Windows
 - Browser Firefox
 - Version 80

**Comment by hifiberry** [comment]
Please do not open feature request as bugs. 
As the version number is just 8 characters, we don't think this is really a problem and won't change this behavior
