### ISSUE TITLE
MPD 0.22 released

### ISSUE THREAD

**Issue by lucasso72** [hifiberry/hifiberry-os#149]
**Is your feature request related to a problem? Please describe.**
The new release of MPD contains a lot of fixes.

**Describe the solution you'd like**
compile and include MPD 0.22 into next release of HiFiBerryOS pls

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hifiberry** [comment]
It's more complex than this as this version isn't just a bugfix release, but requires newer libraries that are not available for our buildroot environment today. 
While we will upgrade mpd at some point, it's probably not gonna happen in the next release.
