### ISSUE TITLE
Web Interface doesn't save configuration

### ISSUE THREAD

**Issue by lucasso72** [hifiberry/hifiberry-os#15]
Using 20191030.
When disabling bluetooth and/or MPD using the webUI at the next reboot they are enabled again.
cheers,
/Luciano

**Comment by hifiberry** [comment]
I can confirm this. It will be fixed in the next release.

**Comment by hifiberry** [comment]
This should be fixed now. Please check the latest version. You can update from command line using
/opt/hifiberry/bin/update

**Comment by lucasso72** [comment]
I confirm it's fixed.

**Comment by hifiberry** [comment]
Thanks.
