### ISSUE TITLE
DLNA not working on 20201020

### ISSUE THREAD

**Issue by schwachstelle** [hifiberry/hifiberry-os#156]
**Describe the bug**
When DLNA is enabled through the web gui, it turns off a few seconds (~10) later.

**HiFiBerryOS version**
20201020

**HiFiBerry sound card**
DAC+ DSP

**To Reproduce**
1. go to 'General' and turn on MPD
2. go to 'Sources' and turn on DLNA
3. wait 10 seconds
4. go to any other page, e.g. start page ('Hifiberry')
5. go to Sources' again and see: DNA is switched off

**Expected behavior**
DLNA should stay switched on and not turn off automatically.

**Screenshots**
no screenshot

**Browser (if applicable)**
 - OS: Linux
 - Browser Firefox
 - Version 81.0

**Additional context**
running on a PI 4.

**Comment by hifiberry** [comment]
I can confirm this bug. We'll fix this in the next bugfix release.

**Comment by schwachstelle** [comment]
Fixed!  :-)
