### ISSUE TITLE
custom splash screen

### ISSUE THREAD

**Issue by stutteringp0et** [hifiberry/hifiberry-os#168]
**Is your feature request related to a problem? Please describe.**
Using the OS with an attached screen, it would be awesome to have the ability to customize the splash screen

**Describe the solution you'd like**
Ideally, I'd like to be able to place a correctly formatted and named image into one of the data directories, and have the boot sequence use that image instead of the default.

**Describe alternatives you've considered**
I've been reading about the process used to create a custom splash screen using psplash (the splash used in hifiberry-os)

**Additional context**
I'm building a portable music system using the beocreate, raspi-4, raspi-touchscreen, a 40v battery, a pair of Bose 101 speakers, and a Pyle subwoofer.  I gave the system a name (The Weapon), and would like the ability to make it boot up with that name on the splash screen.

**Comment by hifiberry** [comment]
This would require to compile your own version as the splash screen is hard-coded and built in during compile time.

**Comment by stutteringp0et** [comment]
@hifiberry would you entertain a pull request to add this functionality?

**Comment by hifiberry** [comment]
Depends on the pull. If you find a way NOT to put in your logo and make it configurable, we might think about it. However, we won't include other logos into our build.

**Comment by stutteringp0et** [comment]
Absolutely, it would default to your current splash screen.

**Comment by hifiberry** [comment]
Not sure how you want to do this. AFAIK psplash doesn't support this. What are you planning to do?

**Comment by stutteringp0et** [comment]
Ubuntu uses plymouth, which allows user configuration, so I was going to look into that.

**Comment by hifiberry** [comment]
Have a look! However, I'm not sure if this can display messages. That's an important feature that we don't want to loose.

**Comment by stutteringp0et** [comment]
Plymouth can display messages.  I wouldn't want to remove any feature to add one.

With your blessing, I'll look at this more closely and come back with a pull request when I have something working.

**Comment by hifiberry** [comment]
Looking forward to this.

**Comment by Leshauts** [comment]
Would be nice to be able to custom (or access html files?) the "Now playing" screen. Like choose a uniform background or make the text of the artsit and the song a bit bigger.
