### ISSUE TITLE
squeezelite volume control using mouse not working

### ISSUE THREAD

**Issue by durgadas311** [hifiberry/hifiberry-os#169]
**Describe the bug**
When using the mouse on HDMI display, the volume control knob reacts to the mouse but cannot be moved. The only way to control the volume is from the Logitec Media Server app on the host, or from a tablet (smart phone). With an attached keyboard, UP/DOWN arrow keys sort-of work (other keys do strange things). I am waiting for the remote control to arrive, so I suspect it will work as the keyboard did.

**HiFiBerryOS version**
20200908

**HiFiBerry sound card**
DAC+ Pro

**To Reproduce**
1. Connect display (HDMI) and mouse (USB)
2. Connect using squeezelite to Logitec Media server
3. click and drag volume control knob - it does not move.

**Expected behavior**
Should be able to drag volume control knob with mouse

**Screenshots**
none

**Browser (if applicable)**
N/A

**Additional context**

**Comment by hifiberry** [comment]
Do you still see this on the latest release?

**Comment by durgadas311** [comment]
This can be closed, for now. once I update I will re-check and if it still exists then will re-open or create a new issue.
