### ISSUE TITLE
Display time-of-day on screen

### ISSUE THREAD

**Issue by durgadas311** [hifiberry/hifiberry-os#171]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete feature requests will be closed.
You should remove this comment before posting the feature request.

**Is your feature request related to a problem? Please describe.**
I'd like to be able to see local time-of-day when viewing the screen.

**Describe the solution you'd like**
Current time displayed 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by hifiberry** [comment]
We might offer a way to use your own HTML templates. However, as the system is designed for a minimalistic look, we will probably never include this in the standard templates.
