### ISSUE TITLE
allow passwords to be viewed when entered to check them

### ISSUE THREAD

**Issue by cwgamma** [hifiberry/hifiberry-os#191]
Most password entry fields permit you to check what you have typed as a password by clicking on a little eye icon to the left of the entry field to make the password visible. That would be much appreciated in the HiFiBerry web app

**Comment by tobiv** [comment]
I should be able to add this. 
@hifiberry Is it possible to only build/run the UI to test this or is it necessary to build the entire OS?

**Comment by hifiberry** [comment]
@tobiv You can't easily run the UI without HiFiBerryOS, but for development, you don't need to build the whole system, but only change the UI and copy it over:
https://github.com/bang-olufsen/create

**Comment by tobiv** [comment]
I created a pull request at https://github.com/bang-olufsen/create/pull/134

**Comment by tobiv** [comment]
Pull request was merged; issue can be closed.
(Note that you'll have to force reload the page (`Ctrl-Shift-R` in most browsers) for this to take effect, once it has been released of course.)
