### ISSUE TITLE
Hifiberry OS builds with libupnp instead of libupnp18

### ISSUE THREAD

**Issue by Nazdravi** [hifiberry/hifiberry-os#194]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
When compiling hifiberry-os the package "libupnp" is selected, but libupnp18 provides version >= 1.8
../buildroot-4/build/hifiberry-mpd-0.22.2/src/lib/upnp/meson.build:1:0: ERROR: Invalid version of dependency, need 'libupnp' ['>= 1.8'] found '1.6.25'.

**HiFiBerryOS version**
You find this on the "About" screen. It looks like Software 20YYMMDD
github sources "master" from december 14th, 2020
buildroot-2020.11
target: raspi4

**HiFiBerry sound card**
Post the exact type, e.g. DAC+ Pro instead of "DAC+".

**To Reproduce**
./build-config 4
./config
./compile

**Expected behavior**

**Screenshots**

**Browser (if applicable)**

**Additional context**

Regards,
Nazdravi

**Comment by hifiberry** [comment]
I guess, you're using an unpatched buildroot version. HiFiBerryOS requires some patches (including libupnp). Therefore, you should retrieve the correct buildroot version using 

./get-buildroot

**Comment by Nazdravi** [comment]
Thanks. Solved.
