### ISSUE TITLE
Serial Port cannot be activated/Does not work

### ISSUE THREAD

**Issue by lukas-hllr** [hifiberry/hifiberry-os#199]
**Describe the bug**
I'm not able to activate the Serial Port in the 'Interact' menu. If I try send to send a serial message on Startup anyways, I'm not able to receive anything. Even if I assume that I used the wrong baudrate (9600?) to receive the message, I can't see the Rx/Receive LED of the Arduino flashing. How do I activate the serial port corretly?

**HiFiBerryOS version**
hifiberryos-20201213-pi3

**HiFiBerry sound card**
PiFi DAC+ v2.0

**To Reproduce**
1. Go to 'INTERACT'
2. Activate interactions
3. Turn on the Serial Port (Nothing happens if I click on 'Serial Port Off', to activate the Port. Bug?)
4. Create any new interaction that sends data via the Serial Port (e.g. on Startup -> send 'Test')
5. Connect Raspberry GPIO 14 (TXD) to Arduino Pin RX0 and Raspberry Pi GND to Arduino GND (Common Ground)
6. Try to recieve the message with an Arduino

**Expected behavior**
I should be able to enable the Serial Port via the Webinterface.
The Arduino should recieve a Serial Message/The Rx/Receive LED should flash.

**Screenshots**
![image](https://user-images.githubusercontent.com/76522403/102998183-f5369180-4526-11eb-8f07-38e1801eacae.png)
![image](https://user-images.githubusercontent.com/76522403/102998197-01baea00-4527-11eb-880d-4f127e35a5c9.png)

**Browser (if applicable)**
 - OS: Windows 10
 - Browser: Microsoft Edge (Chromium)
 - Version: 87.0.664.66

**Comment by hifiberry** [comment]
Looks like you're not using a HiFiBerry sound card. Please first install a genuine HiFiBerry sound card.

**Comment by dodepier** [comment]
I have a hifiberry dac+ dcp on a raspberry pi 3 and can also not active the serial port. Or is the hifiberry dac+ dcp not supported?

**Comment by hifiberry** [comment]
Is it a Pi3B or Pi3 B+? On the 3B+, the serial port is used for Bluetooth

**Comment by dodepier** [comment]
It is a Pi3A+

**Comment by hifiberry** [comment]
Same thing. You would need an USB-serial adapter for this
