### ISSUE TITLE
96kHz Roon playback distorted

### ISSUE THREAD

**Issue by hifiberry** [hifiberry/hifiberry-os#20]
Playback of 96kHz files is distorted
This happens only in non-exclusive mode (if Roon is not the only player that's enabled)

**Comment by hifiberry** [comment]
Workaround: Enable upsampling to 192kHz

**Comment by x838nwy** [comment]
sorry for being a nood at this, but how do I do this?

**Comment by hifiberry** [comment]
Right-click on the device, then select "DSP"/"Sample rate conversion" and select 192kHz output for 96kHz sample rate

**Comment by hifiberry** [comment]
This will be fixed with the new "Direct to hardware" mode that will be enabled by default in the december release

**Comment by hifiberry** [comment]
Switched to direct-to-hardware mode in release 20191219
