### ISSUE TITLE
bugs in mobile webui

### ISSUE THREAD

**Issue by icstyle** [hifiberry/hifiberry-os#201]
**Describe the bug**
On mobile web UI, I can't select other frequency squares in Sound Design. I can only modify the first one (which gets automatically selected). Also in listening modes, I can't select other modes.

**HiFiBerryOS version**
20201213 (problem exists since several months)

**HiFiBerry sound card**
DAC+DSP @ RPi4

**Browser (if applicable)**
 - OS: Android 11
 - Browser: Chrome
 - Version: latest

**Comment by tuomashamalainen** [comment]
Hello and thanks for reporting this. I am able to reproduce this in desktop version of Microsoft Edge with mobile simulation, so I will investigate further.

Sorry for the inconvenience.

Best,
Tuomas from Bang & Olufsen

**Comment by hifiberry** [comment]
We hope this can be fixed in the next release.
