### ISSUE TITLE
No wifi on Raspberry Pi 2

### ISSUE THREAD

**Issue by dheckl** [hifiberry/hifiberry-os#202]
**Describe the bug**
No wifi interface is detected running HiFiBerryOS on Raspberry Pi 2.

**HiFiBerryOS version**
20201213

**HiFiBerry sound card**
DAC+

**To Reproduce**
UI
1. Click on Network

SSH
1. `ifconfig`

**Expected behavior**
A wifi interface should be displayed

**Comment by hifiberry** [comment]
This is normal as the Pi2 doesn't have onboard WiFi. Other WiFi interface are not supported.
