### ISSUE TITLE
An issue with the volume slider.

### ISSUE THREAD

**Issue by skumka** [hifiberry/hifiberry-os#205]
**Describe the bug**
I experience an issue with the volume slider.
It works on a laptop via a web browser, it does not work on a dedicated 7" raspberry touchscreen.

**HiFiBerryOS version**
the latest one from December 2020

**HiFiBerry sound card**
DAC2 HD+DSP

**Expected behavior**
Volume slider on dedicated touchscreen should work like via a web browser.

**Additional context**
HiFiBerry with dedicated 7" raspberry touchscreen

**Comment by skumka** [comment]
Am I the only one seeing this issue?

**Comment by hifiberry** [comment]
There are very few users with a touchscreen. We see if we can reproduce this.

**Comment by eshcheglov** [comment]
One more user with touchscreen is here. Yes, I can confirm this bug. 

Slider works correctly in web interface, but reaction to touchscreen events is unpredictable. Sometimes it works, but only once. Sometimes slider jump to desired position, but then immediately jumps back to previous one. Sometimes it doesn't react to the touch at all. 

I can collect any debug information that you require. 

Version is 20201101, rPI4 + DAC2 HD+

**Comment by stutteringp0et** [comment]
Many touchscreen issues with the december version.  Can't switch between all sound profiles, I can only pick between 2 (of 4).  When a song is playing I can't skip or start a new song from the music player.  it forgot the wifi access point I used while running the upgrade.....all sorts of things aren't right anymore.  I'm going back to the November version when everything worked except switching back from a bluetooth connection.

**Comment by ajmccaus** [comment]
I can confirm the same, no volume control and inconsistent 'now playing' updates on the 7" official touchscreen for the Digi+ and Amp2 HATs with RPi 4.
