### ISSUE TITLE
now playing screen on start-up for Hifiberry OS hdmi 

### ISSUE THREAD

**Issue by installaudio** [hifiberry/hifiberry-os#211]
**Is your feature request related to a problem? Please describe.**
When restarting my hifiberry Dac I need to plug in a mouse each time to click the button in lower left corner to show the now playing screen. 

**Describe the solution you'd like**
On first start up can the now playing screen be showing - users can then click this down if they want to access settings / admin via hdmi.

**Describe alternatives you've considered**
no alternatives known

**Additional context**
I use a hdmi display plugged into a pi4 with DAC HD - the display shows what is playing in the room

**Comment by hifiberry** [comment]
This should be the normal behaviour, but the browser seems to behave a bit strange in the last release. I hope we can fix this.

**Comment by installaudio** [comment]
yes please - bug fix in new version hopefully

**Comment by hifiberry** [comment]
Problem is that it's going well on a "normal" browser and the local browser doesn't have a full javascript console which makes it really hard to debug. It might not be fixed in the next release.

**Comment by hifiberry** [comment]
This has been fixed in the May 21 release
