### ISSUE TITLE
Disable Spotify by default on install

### ISSUE THREAD

**Issue by terrizah** [hifiberry/hifiberry-os#220]
**Is your feature request related to a problem? Please describe.**
During installation on a Pi2 the Spotify daemon takes quite a while to start. Other additional services are already disabled by default.

**Describe the solution you'd like**
Disable Spotify by default on install.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by hifiberry** [comment]
Sorry, but Spotify is quite popular for HiFiBerryOS user, we won't disable this be default. You can disable it by yourself.
