### ISSUE TITLE
Bluetooth source remains visible in web interface after disconnect

### ISSUE THREAD

**Issue by RavanH** [hifiberry/hifiberry-os#222]
**Describe the bug**
When playing music from a phone via bluetooth, the player in the web interface shows the music being played. But after disabling the bluetooth connexion, and then (for example) choosing another source like Radio or Music (via MPD), the player keeps on showing the old disconnected source.

**HiFiBerryOS version**
20201213

**HiFiBerry sound card**
AMP2

**To Reproduce**
1. Connect a phone via bluetooth and play music
2. Go to web interface ans see the player at the bottom show the source and sound track info
3. Disconnect the phone (by disabling bluetooth for example)
4. In the web interface, go to play music from the Library or Radio
5. Notice the player sticks with the sound track from the phone

**Expected behavior**
Player updating to active sound source.

**Browser (if applicable)**
 - OS: Ubuntu 20.10
 - Browser Chrome
 - Version 87

**Additional context**
Original post https://support.hifiberry.com/hc/en-us/community/posts/360014363277--Bug-Bluetooth-source-remains-visible-after-disconnect-in-HifiberryOS-web-interface

**Comment by tobiv** [comment]
Same as #148
