### ISSUE TITLE
Feature Request: Integrated Snapcast Server

### ISSUE THREAD

**Issue by gpatkinson** [hifiberry/hifiberry-os#223]
Hi, I've tried many of the competing projects out there (most recently was using volumio) and I really like hifiberry! Thanks for all your hard work.

I see that HifiberryOS supports connecting to a snapcast server ... what would be really great is if there was one integrated into HifiberryOS so that we can synchronously stream to other rooms. Is this on the roadmap? Thanks for your consideration.

**Comment by hifiberry** [comment]
Not yet on the roadmap. As HiFiBerryOS is designed as a player and not as a server, we'll probably won't look into this soon. However, using Docker it might be possible to implement this. Looking forward to contributions...

BTW: If you want us to leave this open, please use the Feature request template that we provide.

**Comment by gpatkinson** [comment]
Sorry about not using the proper template, noted for next time.

Yeah, I'll see if I can put together an alpine-based image that runs snapcast. Will make a pull request if I can get it working. Thanks again for this great software!
