### ISSUE TITLE
Customize Version

### ISSUE THREAD

**Issue by MatteoEng** [hifiberry/hifiberry-os#224]
**Is your feature request related to a problem? Please describe.**
Hi, is it possible to customize a version of hifiberry?

**Describe the solution you'd like**
 I'll explain myself. I need to personalize the GUI in the browser, for example I need to create a speaker and the name on the product will be *company name*, which files I should change?

**Describe alternatives you've considered**

**Additional context**
Obviously it will be something that won't change your versions/repo, but will be a local edit and in the code credit will give to your project

**Comment by hifiberry** [comment]
We can offer customization services or consulting for customization. These are paid services. Please contact us at support@hifiberry.com to discuss details.
