### ISSUE TITLE
add settings or config file line for screen resolution for small displays - solved

### ISSUE THREAD

**Issue by yvaditya** [hifiberry/hifiberry-os#227]
add setting to change screen resolution, either in menu or in config.txt file

**Comment by yvaditya** [comment]
![IMG_0492](https://user-images.githubusercontent.com/51217772/105621498-ed376f00-5dbc-11eb-8c5f-a545a16e56bf.jpg)
![IMG_0493](https://user-images.githubusercontent.com/51217772/105621500-ef013280-5dbc-11eb-9ef3-278df5d62cd8.jpg)

**Comment by yvaditya** [comment]
trying to build a dac with almost a coverart display, can you add a way to set resolution, and these cheap displays only show up as a 1080p display unless a resolution is pushed in, also a large ui buttons, but this could be though a HTML template. I get you want to maintain the minimal OS look and feel, but also as a os designed for diyers, most of the times these contradict each other. may be add it in the config.txt so only if people how really want it can edit it,

**Comment by hifiberry** [comment]
What exactly did you edit?

**Comment by yvaditya** [comment]
i added this in the config.txt, to set the resolution and refresh rate to the correct ones, 

hdmi_group=2
hdmi_mode=87
hdmi_cvt=800 480 60 6 0 0 0
hdmi_drive=1

**Comment by hifiberry** [comment]
Thank you
