### ISSUE TITLE
Volume set to maximum on device when I mute sound in Spotify

### ISSUE THREAD

**Issue by eshcheglov** [hifiberry/hifiberry-os#228]
**Describe the bug**
When I set volume to "0" in Spotify using both Spotify Web or Mobile Client, DAC volume jumps to 100% instead 

**HiFiBerryOS version**
20201101

**HiFiBerry sound card**
DAC2 HD

**To Reproduce**
1. Enable "Spotify Connect" source
2. Start playing 
3. Try to set volume to zero using Spotify Web or Spotify Mobile client
4. DAC Volume automatically jump to 100%, however Spotify interface will report 0% 

**Expected behavior**
Spotify become muted

I can see this jump using Alsamixer. When I use my phone volume buttons to lower the volume, "DAC" slider in alsamixer correctly go down to "2" but then jumps to "100"

**Comment by hifiberry** [comment]
This is a really old issue and we haven't heard about any problems like this for a long time. Therefore, I'll close this.
