### ISSUE TITLE
Individually change bluetooth and airplay device name

### ISSUE THREAD

**Issue by bglnelissen** [hifiberry/hifiberry-os#234]
**Is your feature request related to a problem? Please describe.**
I use the HiFiBerry-os to stream music to, and have AirPlay and bluetooth enabled. HiFiBerry-os announces both AirPlay and Bluetooth with the same name. For the client (Mac running Music) it is unclear if I send my audio over AirPlay or over bluetooth. 

**Describe the solution you'd like**
I would like to be able to change the name of my AirPlay service and the name of the bluetooth service. This way it is clear to which service I am streaming my music to.

**Describe alternatives you've considered**
I am thinking about changing the `shairport-sync` config files, but this might break during an update.

**Additional context**
My HiFiBerry-os is called 'KoekoekHiFi', which is bluetooth, and which is AirPlay? (All in Dutch, but the point should be clear)

![Screen Shot 2021-02-06 at 10 02 34](https://user-images.githubusercontent.com/6543659/107114143-02ec7000-6864-11eb-82a5-abf5e60e9e05.png)

**Comment by usul27** [comment]
The easiest way is either to disable BT or edit /etc/bluetooth/main.conf
