### ISSUE TITLE
not visible song cover after disconnecting from bluetooth

### ISSUE THREAD

**Issue by Zagii** [hifiberry/hifiberry-os#239]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
After connecting my phone to hifiberryOS via blootooth and disconnecting bloototh the graphic and the title of songs freeze

log from XXXX:81//api/player/status
 {"players": [{"name": "mpd", "state": "paused", "artist": null, "title": null, "supported_commands": ["Next", "Previous", "Pause", "PlayPause", "Stop", "Play", "Seek", "Random", "RandomOff", "RepeatAll", "RepeatOff"]}, {"name": "spotify", "state": "paused", "artist": "Ben Harper", "title": "Burn One Down", "supported_commands": ["Next", "Previous", "Pause", "PlayPause", "Play"]}, {"name": "dlna", "state": "stopped", "artist": null, "title": null, "supported_commands": ["stop", "play"]}, {"name": "ShairportSync", "state": "stopped", "artist": null, "title": null, "supported_commands": ["stop", "pause", "next", "previous", "play"]}, {"name": "mojMi9", "state": "paused", "artist": "", "title": "LTspice audio simulation", "supported_commands": ["stop", "pause", "next", "previous", "play", "seek"]}], "last_updated": "2021-02-11 08:35:00.277161"}

**HiFiBerryOS version**
You find this on the "About" screen. It looks like Software 20YYMMDD
20210203

**HiFiBerry sound card**
Post the exact type, e.g. DAC+ Pro instead of "DAC+".
DAC2 + Pro (visible as DAC+/Amp2)

**To Reproduce**
Steps 
1 connect to phone via BT ->ok
2 visible connection on phone and hifiberryOS
3 play songs from phone ->ok
4 disconnect bluetooth -> ok
5 still the same graphics on hifiberryOS (even if bluetooth was turned off)

playing radios, spotify etc not changing song title and cover graphic

**Expected behavior**
properly rendered song info

**Screenshots**

**Browser (if applicable)**
androidOS (chrome)
PC windows (chrome)

**Additional context**

**Comment by tobiv** [comment]
Same as #148
