### ISSUE TITLE
python-alsaaudio stale package

### ISSUE THREAD

**Issue by tysonnorris** [hifiberry/hifiberry-os#241]
**Describe the bug**
Using python-alsaaudio to read input causes warnings:
```
DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
```
I think this can be remedied with a newer version (0.9.0) of python-alsaaudio

**HiFiBerryOS version**
20210209

**HiFiBerry sound card**
N/A

**To Reproduce**
1. create a python script to read audio input e.g. 
```
input = aa.PCM(aa.PCM_CAPTURE, aa.PCM_NORMAL, device="hw:1,1")
 (dl, data) = input.read()
```
3. run the script
4. See the warnings
```
DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  (dl, data) = input.read()
```

**Expected behavior**
No warnings

**Screenshots**
N/A

**Browser (if applicable)**
N/A

**Additional context**
I think this can be adjusted in the buildroot patch file, I will submit a PR in the future if it doesn't get fixed before I get there.

**Comment by hifiberry** [comment]
We will upgrade this at some point. However, as the versions are incompatible, this required more changes and testing and probably won't be in the next release(s).
