### ISSUE TITLE
Web Server Issue on New Install of 20210203 on RPi4

### ISSUE THREAD

**Issue by rcollinsef** [hifiberry/hifiberry-os#242]
New Install and on boot up I get startup screen, RPi gets IP from DHCP and is pingable. It shows up as an AirPlay destination. However I can't get to WebUI and local HDMI output shows Page load error "Could Not Connect: Connection Refused" on http://localhost/#now-playing. It seems like the web server portion is not loading correctly.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/55929211/107905976-09db4880-6f1e-11eb-8408-1b186b2d0b89.png">

**Comment by hifiberry** [comment]
Please use the correct bug report template.
