### ISSUE TITLE
Blank screen after a configurable timeout

### ISSUE THREAD

**Issue by akelge** [hifiberry/hifiberry-os#245]
**Is your feature request related to a problem? Please describe.**
It would be cool to be able to configure the screen blanking while using a local display.

**Describe the solution you'd like**
In the Display settings there should be a `Blank screen timeout` field 

**Describe alternatives you've considered**
I already did manually the change, editing the file `/etc/xdg/weston/weston.ini` and setting `idle-time` to 300 and it works.

**Additional context**
Nothing else to add

**Comment by hifiberry** [comment]
There will be some screen saver stuff bases on a user contribution in the next release (works differently).
