### ISSUE TITLE
Set Codec order in squeezelite

### ISSUE THREAD

**Issue by gaetanars** [hifiberry/hifiberry-os#246]
**Is your feature request related to a problem? Please describe.**
In my home I force some of my squeezelite to run in PCM only (my LMS convert FLAC or MP3 to PCM). For this I run Squeezelite with `-c pcm,flac,mp3`

**Describe the solution you'd like**
Is it possible to add this parameters on HifiberryOS interface?

**Describe alternatives you've considered**

**Additional context**

**Comment by usul27** [comment]
If we add this to the UI, it would end up like some other distributions that have tons of configuration options that most users don't understand. We won't add this to the GUI, but you can edit the configuration file directly.

**Comment by gaetanars** [comment]
Ok I understand this point of view. This is also this settings that can be add in an « advanced settings » section.
