### ISSUE TITLE
I2c not enabled on boot

### ISSUE THREAD

**Issue by Bertware** [hifiberry/hifiberry-os#255]
**Describe the bug**
i2c communication is not enabled on startup. `modprobe i2c-dev` is required to enable i2c.

**HiFiBerryOS version**
20210203

**HiFiBerry sound card**
DAC+ADC Pro

**To Reproduce**
Install a v202011xx build on a rpi3b, upgrade to 20210203. The same bug might arise with clean installs of 20210203, but I have not tested this. Trying to use i2c will lead to  `No such file or directory: '/dev/i2c-1'`. Running `modprobe i2c-dev` activates i2c, resolving the issue

**Expected behavior**
i2c should be enabled by default

**Additional context**
The (unmodified) `/boot/config.txt` contains the following lines regarding i2c:

```
dtparam=i2c=on
dtparam=spi=on
dtoverlay=i2c-gpio,i2c_gpio_sda=0,i2c_gpio_scl=1
```

**Comment by hifiberry** [comment]
It's not a bug, but is should be like this as no I2C is usually needed
