### ISSUE TITLE
BUG: Album has empty list of songs

### ISSUE THREAD

**Issue by MTxx87** [hifiberry/hifiberry-os#261]
**Describe the bug**
One of the albums on the USB stick connected to the RP shows empty list of songs despite all files being there.

**HiFiBerryOS version**
20210408

**HiFiBerry sound card**
Hifiberry DIGI plus

**To Reproduce**
1. Go to http://hifiberry.local/
2. click Sources
3. click Music
4. select Artist 
5. select Album
6. BUG: view is empty (see screenshots below)

**Expected behavior**
The list of songs should be on the view.

**Screenshots**
![Screen Shot 2021-05-05 at 20 30 20](https://user-images.githubusercontent.com/12138301/117191646-16ff2980-ade1-11eb-89a1-05e7de97eeee.jpg)
![Screen Shot 2021-05-05 at 20 30 27](https://user-images.githubusercontent.com/12138301/117191654-19fa1a00-ade1-11eb-939d-5ef806df4cdf.jpg)
![Screen Shot 2021-05-05 at 20 31 22](https://user-images.githubusercontent.com/12138301/117191662-1c5c7400-ade1-11eb-9501-7ce923b88845.jpg)

**Browser (if applicable)**
 - OS: MacOS
 - Browser Safari (Version 14.1 ) / Chrome (Version 90.0.4430.93)

**Additional context**
Console error says:

`vue.js:634 [Vue warn]: Error in render: "RangeError: Invalid time value"
vue.js:1897 RangeError: Invalid time value
    at Vue.time (music-client.js:279)
    at eval (eval at createFunction (vue.js:11649), <anonymous>:3:6709)
    at Proxy.renderList (vue.js:2637)
    at eval (eval at createFunction (vue.js:11649), <anonymous>:3:6613)
    at Proxy.renderList (vue.js:2637)
    at eval (eval at createFunction (vue.js:11649), <anonymous>:3:6487)
    at Proxy.renderList (vue.js:2637)
    at Proxy.eval (eval at createFunction (vue.js:11649), <anonymous>:3:3178)
    at Vue._render (vue.js:3551)
    at Vue.updateComponent (vue.js:4067)`
    
As far as I know, the songs files are not corrupted and have all their meta in place.
I have compared them to the other FLAC files I have on the USB stick (which are all working).

**Comment by hifiberry** [comment]
Usually this is a problem of missing/incorrect metadata. Check the metadata with an tag editor.

**Comment by ssws** [comment]
Hi, thanks for the reply.

I have edited and checked the meta.
Here is a screenshot I have taken from MusicBrainz Picard app.

![Screen Shot 2021-05-06 at 09 37 26](https://user-images.githubusercontent.com/4726183/117260385-519fab00-ae4f-11eb-89d9-5e4132bcc56f.jpg)

Please advise if you see something incorrect.
I couldn't find anything wrong.

Since the error in the console mentioned an error on the date, 
I tried both having the date set as year only (1991) or to a full date (1991-05-06), 
but no success.

If can help I can also share the file.

**Comment by MTxx87** [comment]
Hi, thanks for the reply.

I have edited and checked the meta.
Here is a screenshot I have taken from MusicBrainz Picard app.

![Screen Shot 2021-05-06 at 09 37 26](https://user-images.githubusercontent.com/4726183/117260385-519fab00-ae4f-11eb-89d9-5e4132bcc56f.jpg)

Please advise if you see something incorrect.
I couldn't find anything wrong.

Since the error in the console mentioned an error on the date, 
I tried both having the date set as year only (1991) or to a full date (1991-05-06), 
but no success.

If can help I can also share the file.

**Comment by MTxx87** [comment]
As @hifiberry pointed out, it was a problem of metadata.

In case somebody else have the same problem:
manually changing metadata using MusicBrainz didn't work for me.
It started working perfectly only after I used the 'lookup' function and let the software assign the metadata for me.
