### ISSUE TITLE
RPi0 Spotify is Showing but not Working

### ISSUE THREAD

**Issue by Edocsyl** [hifiberry/hifiberry-os#264]
**Describe the bug**
Spotify Source is not shown in the Source Section of the Hifiberry Webinterface, in the Diagnostic section its shown as running and also in the Spotify Client. When you try to connect to the Source, no connection can be established. 

**HiFiBerryOS version**
210203

**HiFiBerry sound card**
DAC+ ZERO

**Expected behavior**
Spotify should not be shown in the spotify client because there is a limitation on the RP0

**Additional context**
The webseite describes some limitations about the RP0 (https://www.hifiberry.com/hifiberryos)

**Comment by hifiberry** [comment]
We'll try to fix this. As Pi Zero releases aren't tested, this might or might not work well.
