### ISSUE TITLE
Spotify connect stop playing after using Bluetooth

### ISSUE THREAD

**Issue by 3579km** [hifiberry/hifiberry-os#266]
**Describe the bug**
Spotify connect stop playing after using Bluetooth. Playback stops after ~10 seconds

**HiFiBerryOS version**
20210408
Raspberry Pi 4

**HiFiBerry sound card**
DAC2 HD

**To Reproduce**
1. Play music using bluetooth as source
2. Stop playing music via bluetooth and disconnect from device menu (for me it's Windows 10 computer, Bluetooth menu setup)
3. Start playing with Spotify connect. After about 10 second playback stops

**Expected behavior**
Never stop playing

**Additional context**
Restarting from web interface solves this issue

**Comment by hifiberry** [comment]
I don't have a Win10 system with BT available, but tested with an iPhone. I can't reproduce the problem with this. Did you try the latest HiFiBerryOS version already?
