### ISSUE TITLE
Sound-card DAC+ light no sound settings

### ISSUE THREAD

**Issue by dodepier** [hifiberry/hifiberry-os#27]
Hello,

I just installed hifiberry-os on a raspberry pi 3 A+ with a DAC+ light. Works great I have sound. But I am not sure if hifiberry-os did used the correct sound drivers. I have some noise in the output and in the sound config page the sound card is Unknown. There are also no settings available for the sound card. Is this correct?
![image](https://user-images.githubusercontent.com/33546352/72371595-fbac6e80-3704-11ea-9d30-c49d82b8cb8e.png)
This are my diagnostics files:
[amixer.txt](https://github.com/hifiberry/hifiberry-os/files/4060827/amixer.txt)
[aplay.txt](https://github.com/hifiberry/hifiberry-os/files/4060828/aplay.txt)
[arecord.txt](https://github.com/hifiberry/hifiberry-os/files/4060829/arecord.txt)
[asound.conf.txt](https://github.com/hifiberry/hifiberry-os/files/4060857/asound.conf.txt)
[df.txt](https://github.com/hifiberry/hifiberry-os/files/4060830/df.txt)
[hifiberry.state.txt](https://github.com/hifiberry/hifiberry-os/files/4060862/hifiberry.state.txt)
[hw_params.0.txt](https://github.com/hifiberry/hifiberry-os/files/4060831/hw_params.0.txt)
[hw_params.1.txt] empty 
[hw_params.2.txt] empty 
[playerstate.txt](https://github.com/hifiberry/hifiberry-os/files/4060832/playerstate.txt)
[systemctl.txt](https://github.com/hifiberry/hifiberry-os/files/4060833/systemctl.txt)
[top.txt](https://github.com/hifiberry/hifiberry-os/files/4060834/top.txt)
[version.txt](https://github.com/hifiberry/hifiberry-os/files/4060835/version.txt)

**Comment by hifiberry** [comment]
That's fine. Sound settings are only available for DSP based cards (Beocreate and DAC+ DSP)

**Comment by dodepier** [comment]
Thanks for the quick replay! I have one other question: How can I set a (software)volume limit for the DAC+ light? Since I cannot use the dsptoolkit.

**Comment by hifiberry** [comment]
You can't. I recommend just selecting the maximum volume on your amplifier that's connected to the DAC+ Light.

**Comment by dodepier** [comment]
Ok I have no volume on my amplifier that is the reason I want a limit. Is the solution to buy a HIFIBERRY DAC+ PRO?

**Comment by dodepier** [comment]
> That's fine. Sound settings are only available for DSP based cards (Beocreate and DAC+ DSP)

Maybe it is nice to auto recognise the DAC+ Light when its installed? And change the 'UNKNOWN' to HIFIBERRY DAC+ light. So the user knows that this card has no extra sound options and its installed correct.

**Comment by hifiberry** [comment]
Volume limit is only available for DSP-enabled cards. You would need a DAC+ DSP for this.

We'll see that we can improve the text on the sound settings page.

**Comment by tuomashamalainen** [comment]
Thanks for reporting this. We'll make this text clearer about what it means in the next update.

Tuomas from Bang & Olufsen

**Comment by hifiberry** [comment]
Please try updating to the new version. The DAC+ Light should now be shown as DAC+ Light/Zero/MiniAmp.

**Comment by kmplngj** [comment]
`

pcm.!default {
    type plug
    slave.pcm amp
}

pcm.amp {
  type plug
  slave.pcm "plughw"
  ttable {
    0.0=    0.7     #amplication factor
    1.1=    0.7     #amplication factor
  }
}
`
Would something like this alsa mixer config work for limiting the max volume?

**Comment by hifiberry** [comment]
You can try, but this will be overwritten by updates as the asound.conf is managed by HiFiBerryOS and not supposed to be changed by the user.

**Comment by hifiberry** [comment]
As there was no feedback on this, we'll close this bug. From our point of view, this should be fixed with the January release.
