### ISSUE TITLE
Unknown update delivered (20210531), possible security issue?

### ISSUE THREAD

**Issue by eproxus** [hifiberry/hifiberry-os#272]
**Describe the bug**
A new update was delivered for version `20210531`. However, no such version exist on GitHub and no commits were made that date on either the `master` or `development` branch. I haven’t found any other announcements in the community forum or on the web page.

Is this a real update or a possibly malicious one?

**HiFiBerryOS version**
Upgrade from `20210408` to `20210531`.

**HiFiBerry sound card**
Not relevant. 

**To Reproduce**
1. Try to upgrade HiFiBerry OS. 

**Expected behavior**
The release is publicly available, and can be verified. A changelog exists, and a Git tag with the commits that are included in the release is available.

**Comment by hifiberry** [comment]
This is just a real release, that's not been tagged yet in Github.
