### ISSUE TITLE
Pause-all can't pause snapcast (snapclient)

### ISSUE THREAD

**Issue by Bertware** [hifiberry/hifiberry-os#279]
**Describe the bug**
When snapclient should be paused, the pause-all process fails

**HiFiBerryOS version**
20210531, previous releases had the bug as well

**HiFiBerry sound card**
DAC+ADC Pro

**To Reproduce**
1. Enable Alsaloop (Analog input) and snapcast
2. Play music through the analog input
3. Error is printed to logs: `20210728-003914 20210728-003924 pause-all alsaloop failed, snapclien still running`
4. Alsaloop doesn't start playing since the output device is occupied

**Expected behavior**
Snapcast/snapclient gets stopped, Alsaloop starts playing

**Additional context**
See https://github.com/hifiberry/hifiberry-os/blob/development/buildroot/package/hifiberry-tools/pause-all#L95, which defines "snapcast" as a possible name, but not "snapclien"
Call originates from https://github.com/hifiberry/alsaloop/blob/master/alsaloop.py#L181

**Comment by ewlumpkin** [comment]
It looks like it keeps respawning this process even after it's killed.

**Comment by hifiberry** [comment]
Probably fixed with https://github.com/hifiberry/hifiberry-os/issues/312
