### ISSUE TITLE
OpenHome: wrong room name

### ISSUE THREAD

**Issue by droebbel** [hifiberry/hifiberry-os#284]
OK, this is really cosmetic, but still...

**Describe the bug**
The room name configured for the OpenHome renderer is ignored. Instead, the room name for the UPnP renderer is used.

**HiFiBerryOS version**
20210804

**HiFiBerry sound card**
Beocreate

**To Reproduce**
1. Activate OpenHome
2. Change room name.
3. Check room name with an OpenHome control point (e.g. BubbleDS)

**Expected behavior**
The room name for the renderer should reflect the change :)

**Additional context**
The room name was changed correctly in /etc/upmpdcli.conf. However, the line was still commented out.
I removed the comment and restarted upmpdcli with no effect.

I then tried the following configuration:
```
# "Friendly Name" for the UPnP Media Renderer.
friendlyname = TestU
...
# The name of the room where the Product is located.
ohproductroom = TestO
```
The room name shown by BubbleDS was TestU.
BubbleDS does not work with UPnP renderers at all, and I doubleckecked that it is indeed seeing the right (OpenHome)renderer. 
BubbleUPnP sees both renderers, presenting them as "TestU" and "TestU-UPnP/AV"

**Comment by hifiberry** [comment]
Unfortunately if it's in the configruation, there's nothing we can do here. It's probably best to report this to the upmpdcli developer.
