### ISSUE TITLE
Room Correction, no Sweep

### ISSUE THREAD

**Issue by Jacco192** [hifiberry/hifiberry-os#285]
**Describe the bug**
The room correction option doesn't work as expected. When I start the room correction option and connect the microphone it is recognized and the room measurement starts, during the recording period there is silence and no sweep. I was playing around with the room correction and managed to get just one sweep, 1 out of 10 trials. How many sweeps should be expected during a recording ?
 
HifiBerryOS, PI 4, Digi2 Pro, DSP

**HiFiBerryOS version**
20210804

**HiFiBerry sound card**
Digi2 Pro with DSP

**To Reproduce**
Start room correction.

**Expected behavior**
Sweep to record for setting the room correction

**Comment by hifiberry** [comment]
Try the following:

- login via SSH
- run 
  /opt/hifiberry/bin/run-measurements
  
If this still doesn't output a sweep, run

/opt/hifiberry/bin/pause-all

and run the 

 /opt/hifiberry/bin/run-measurements

again

**Comment by Jacco192** [comment]
Solved, /opt/hifiberry/bin/pause-all did the trick.
Running room compensation from the GUI gives me now 4 sweeps, nice.
Thanks !

**Comment by hifiberry** [comment]
Ok, we'll include this into the measurement script

**Comment by hifiberry** [comment]
Fixed in the new release.
