### ISSUE TITLE
AirPlay Message

### ISSUE THREAD

**Issue by cfhsu** [hifiberry/hifiberry-os#286]
**Describe the bug**
The message showing AirPlay being turned on/off still displays AirPlay 1

**HiFiBerryOS version**
Software 20210804

**HiFiBerry sound card**
DAC+ DSP

**To Reproduce**
1. Go to 'Source'
2. Click on 'AirPlay'
3. Click on 'On'

**Expected behavior**
While the latest HIFiBerry OS supports AirPlay 2, the message is still showing AirPlay 1

**Screenshots**

**Browser (if applicable)**

**Additional context**

**Comment by hifiberry** [comment]
This will be fixed in the next release.
