### ISSUE TITLE
Unable to connect to WLAN with 802.11w Management Frame Protection enabled

### ISSUE THREAD

**Issue by rvk** [hifiberry/hifiberry-os#287]
Hifiberry is unable to connect when 802.11w Management Frame Protection is even optional in the network. When set to disabled, WLAN connection works fine.

Tested with current stable Hifiberry OS on Pi 4. Access point is TP-Link Archer C7 running OpenWRT 19.07.5. Encryption is set to WPA2-PSK.

**Comment by hifiberry** [comment]
If you can propose configuration changes, that would help. We don't have any OpenWRT devices and therefore can't debug/fix this.
