### ISSUE TITLE
Radio is restarted automatically after it has been stopped

### ISSUE THREAD

**Issue by yubiuser** [hifiberry/hifiberry-os#290]
**Describe the bug**
Radio is restarted automatically after it has been stopped.

**HiFiBerryOS version**
20210804
**HiFiBerry sound card**
"DAC+ADC".

**To Reproduce**
1. Start playing a radio stream
2. Click on `Stop`
3. See how Music is restarted a second later

**Expected behavior**
After stopping, music should stay off.

**Additional context**
It doesn't happen every time but has happend a few times now. I'm not sure how to reproduce it reliable. 

![Peek 2021-09-09 10-23](https://user-images.githubusercontent.com/26622301/132651433-0c4eccc7-e18d-45e2-8f11-f9dcefc33f77.gif)

**Comment by hifiberry** [comment]
This is quite interesting. Unfortunately I can't reproduce it here. What Pi are you using?

**Comment by yubiuser** [comment]
It's a Pi4

**Comment by hifiberry** [comment]
Interesting. What other players are enabled?

**Comment by yubiuser** [comment]
Bluetooth, Airpaly, Spotify, Music, Radio

**Comment by hifiberry** [comment]
Try disabling the other sources and see if this changes something - especially Bluetooth.

**Comment by yubiuser** [comment]
Ok, I'll test a bit

**Comment by hifiberry** [comment]
Any feedback on this?

**Comment by hazet42** [comment]
Same problem here - only that I am using HifiBerry OS on a raspberry Pi 3 with HifiBerry DAC+ ADC. Sources enabled are Music, OpenHome and Radio. Can I do something to help with this issue?

**Comment by yubiuser** [comment]
I could not reproduce the issue with the latest version.
