### ISSUE TITLE
Wi-Fi is turned on itself after some time

### ISSUE THREAD

**Issue by sloe10** [hifiberry/hifiberry-os#296]
**Describe the bug**
When i disable WiFi via web gui, it will turn on itself after some time. Maybe after udpdate or restart, i am not sure.

**HiFiBerryOS version**
20210804

**HiFiBerry sound card**
DAC+ Pro

**To Reproduce**
1. Disable Wi-Fi
2. Leave it for some time (weeks)
3. Wifi is turned on again

**Expected behavior**
When i disable it, it is disabled.

**Additional context**
Is there any other way how to disable it forever? I am using only cable connection. Maybe edit /boot/config.txt? Is it persistent between software updates?

**Comment by hifiberry** [comment]
This happens if it looses network connectivity:

https://github.com/hifiberry/hifiberry-os/issues/260
