### ISSUE TITLE
Updater fails on Pi Zero W because PIVERSION is reported incorrectly

### ISSUE THREAD

**Issue by 0bmxa** [hifiberry/hifiberry-os#297]
First of all: I am aware the Pi Zero W is not officially supported. But I'd still like to report this issue here, in case others come across this as well, and because I have the feeling this might be quite an easy fix for you. ;)

---

**Describe the bug**
The firmware updater on the Pi Zero W fails with exit code 1, because it cannot find the correct update URL.

Reason seems to be that `/etc/hifiberry.state` is consulted for a few parameters here: https://github.com/hifiberry/hifiberry-os/blob/master/buildroot/package/hifiberry-updater/update#L10 — one of which being `PIVERSION`.

This was set to `PIVERSION=0` (on my Zero W) resulting in the update URL `https://musicdb.hifiberry.com/updater-url/20210804/0/zip` (note the `/0/`).
Manually changing it to `PIVERSION=0w` fixes the issue and the update starts successfully.

The update fails both when run via the Web UI, but also when calling `/opt/hifiberry/bin/update`.

**HiFiBerryOS version**
20210203

**HiFiBerry sound card**
DAC+ Zero

**To Reproduce**
Preconditions: Use a Pi Zero W, and be on an older firmware version.

Web UI:
1. Navigate to the Software Update section, and see an available update.
2. Click the Software Update button
3. Observe that nothing happens (also no error)

Command line:
1. Run `/opt/hifiberry/bin/update --simulate --critical` (or any other track)
2. Observe the error `No updater found for 20210804/0` and exit code 1.
3. Run `cat /etc/hifiberry.state`, and note `PIVERSION=0` (instead of `0w`)

**Expected behavior**
The update running successfully (via the Web UI).
(And `PIVERSION=0w` set correctly.)

**Screenshots**
N/A

**Browser (if applicable)**
N/A

**Additional context**
The problem reappears after a successful firmware update, i.e. `PIVERSION` is set to `0` again.
I sadly don't know when/where `/etc/hifiberry.state` is written, otherwise I could have included more details on the origin of the issue.

**Comment by pinballpower** [comment]
Thanks for reporting this. We'll fix this in the updater.

**Comment by hifiberry** [comment]
Thank you for reporting this. We'll fix this in the updater.
