### ISSUE TITLE
Problem with Hifiberry AirPlay support after iOS 15.1 / macOS 12 upgrade

### ISSUE THREAD

**Issue by eman676** [hifiberry/hifiberry-os#298]
**Describe the bug**
There is some problem with AirPlay support on Hifiberry OS after iOS 15.1 / macOS 12 upgrade.
Device is connected but it's silent and I see error in macOS console:

AirPlayXPCHelper APSEventRecorderRecordEventWithFlags:507: false condition

It looks like a first handshake problem. When first device is a Apple device and you adding a Hifiberry to connection everything works fine.

**HiFiBerryOS version**
20210804

**HiFiBerry sound card**
Amp2

**To Reproduce**
1. iOS or Mac device as a audio source.
2. Hifiberry as a audio destination via AirPlay protocol. 

**Expected behavior**
Quite obvious - loud and clear music :-)

**Screenshots**

**Browser (if applicable)**
- iOS 15.1
- macOS 12.0.1

**Additional context**
-

**Comment by DaleEMartin** [comment]
I came here to report this issue as well. I don't see any report in the shairport-sync issues.

**Comment by hifiberry** [comment]
Running the latest experimental release  (/opt/hifiberry/bin/update --experimental) works fine here. However what doesn't work is the handover from other players. If there is some other source playing and you start Airplay, it gets stuck as the scripting interface seems to have changed. 

Try the following:
- upgrade to the latest experimental
- make sure no source is playing
- connect and start Airplay

**Comment by hifiberry** [comment]
Handover problem from other players is just a configuration problem that we'll fix soon.

**Comment by fschoell** [comment]
Had a similar issue where Airplay would drop the connection after a couple of seconds and didn't play any sound. This also came up after upgrading to 12.0.1 / 15.1. Had this issue on 20210804 as well as after upgrading to 20210917.

20211103 seems to have this fixed though.

**Comment by hifiberry** [comment]
Thanks for the feedback. I'll package a new experimental with the play/pause bugfix soon and I expect we can release the new version next week.

**Comment by fabvis** [comment]
Work fine with the latest expérimental upgrade

**Comment by hifiberry** [comment]
Ok, this has now been published as "latest", please check if this is fine.

**Comment by eman676** [comment]
It's working!
So, I'm waiting for a official release. :-)

**Comment by hifiberry** [comment]
The official release is the same as the experimental :-)
