### ISSUE TITLE
Undocumented new (20211105) version on https://www.hifiberry.com/hifiberryos/

### ISSUE THREAD

**Issue by HansSchukkink** [hifiberry/hifiberry-os#299]
**Describe the bug**
There is a new version on https://www.hifiberry.com/images/hifiberryos-pi3.zip.
After unpacking this results in hifiberryos-20211105-pi3.img
This is NEWER than 'latest' on https://github.com/hifiberry/hifiberry-os/releases
~~And the problem is that it does not boot. (3B+ with AMP+), 32GB microSD.~~

**HiFiBerryOS version**
20211105

**HiFiBerry sound card**
AMP+

**To Reproduce**
~~Flash the image and try to boot.~~

**Expected behavior**
~~I expect it to boot.~~

**Screenshots**
N/A

**Browser (if applicable)**
N/A

**Additional context**
N/A

**Comment by HansSchukkink** [comment]
Actual boot problem was likely due to defect SD card. Only minor problem is that the version is not documented on github.

**Comment by pinballpower** [comment]
We usually test the latest experimental with some users before pushing it as the "latest" version to the updater and to Github. This is the reason for this newer release on our web site. We expect this to become the "latest" version soon.

**Comment by hifiberry** [comment]
We usually test the latest experimental with some users before pushing it as the "latest" version to the updater and to Github. This is the reason for this newer release on our web site. We expect this to become the "latest" version soon.
