### ISSUE TITLE
How do I build the OS? Error: Your old configuration uses legacy options

### ISSUE THREAD

**Issue by theblond** [hifiberry/hifiberry-os#301]
**Describe the bug**
I try to build a Hifiberry OS image, but I got an error message that I use an old configuration with legacy options.

**To Reproduce**
I downloaded the git repository of Buildroot and Hifiberry OS and followed the steps described here: [building.md](https://github.com/hifiberry/hifiberry-os/blob/master/doc/building.md)
In detail I did:
`./build config 4` (that worked)
`./compile 4` (this does not)

**Expected behavior**
Is the standard configuration here on Github not meant to work?

**Screenshots**
![image](https://user-images.githubusercontent.com/45814725/141127941-99fd0323-adfe-431a-94d2-d8c3443a56f6.png)
![image](https://user-images.githubusercontent.com/45814725/141128024-45bc3d1a-caf1-48f1-9f80-29bca2d0f536.png)

**Comment by hifiberry** [comment]
You need to use the get-buildroot script to download and patch the correct buildroot version.

**Comment by theblond** [comment]
got it, thank you!
