### ISSUE TITLE
Beocreate 4 channel amplifier incorrectly detected as DAC+ DSP in 20211105

### ISSUE THREAD

**Issue by thefiddler** [hifiberry/hifiberry-os#303]
**Describe the bug**
Beocreate 4 channel amplifier is incorrectly detected as DAC+ DSP. No sound.

**HiFiBerryOS version**
20211105

**HiFiBerry sound card**
Beocreate 4 channel amplifier

**To Reproduce**
1. Install an AMP2 and configure it - works fine
2. Replace the AMP2 with a Beocreate - appears as DAC+ DSP instead
3. Try to play any sound (airplay or bluetooth) - no sound

**Expected behavior**
Beocreate 4 channel amplifier should be detected and used.

**Screenshots**
![image](https://user-images.githubusercontent.com/3104289/141538646-854e5f2a-dde8-4f12-94ab-ebaeab351919.png)

**Browser (if applicable)**
 - OS: MacOS
 - Browser: firefox
 - Version: 94

**Additional context**
I was successfully using AMP2 before.

After installing the Beocreate, the DSP program was listed as **Unknown Program**.

I followed the instructions from Norbert here https://support.hifiberry.com/hc/en-us/community/posts/4409631891217-Improved-DAC-DSP-Beocreate-detection:
- `dsptoolkit install-profile /opt/beocreate/beo-dsp-programs/beocreate-universal-10.xml` made the DSP program appear as Beocreate Universal (see screenshot below)
- `nano /etc/hifiberry/config.fixed` made the Beocreate be detected - however it made the DSP disappear!
- however still no sound out of the speakers. (Note: I have removed the mute jumper, so that's not it)

![image](https://user-images.githubusercontent.com/3104289/141539160-39d62b8f-e70c-44da-a2ba-fa38c661e1c9.png)

**Comment by thefiddler** [comment]
If I run `/opt/hifiberry/bin/reconfigure-players` **without** a `/etc/hifiberry/config.fixed` I get the wrong sound card (DAC+ DSP):
```
/opt/hifiberry/bin/readhat: line 23: /sys/class/i2c-adapter/i2c-/new_device: No such file or directory
/etc/hifiberry ~
~
Feature pi not yet configured
Feature dsp not yet configured
Sound card settings have been changed, reconfiguring...
Applying settings:
 Players:  (was )
 Raspberry Pi model: 4
 System name: egli-hifi (was egli-hifi)
 Sound card: DAC+ DSP (was Beocreate 4-Channel Amplifier)
 Interrupt pin for power controller: 2 (was )
 DSP type: DAC+ DSP (was )
 HW device: card 0 (was card 0)
 ALSA mixer control: DSPVolume (was DSPVolume)
 Recording:  (was )
 Vendor/product   (was )
 Features: pi bluetooth pi3orlater arm7 dsp toslink localui (was !)

Saving settings to /etc/hifiberry.state
Reconfigure features
Reconfiguring Spotifyd
Reconfiguring Vollibrespot
Reconfiguring Shairport-sync
Reconfiguring Bluetooth
Reconfiguring squeezelite
Reconfiguring MPD
Reconfiguring DLNA
Reconfiguring Mopidy
modidy not installed, ignoring
Reconfigure AudioControl2
 updated interrupt pin
Restarting audiocontrol2
Reconfigure upmpdcli
Reconfigure RAAT
Configuring RAAT server for UUID 78142091-3786-441b-9c55-94a1a9e9e085 on DAC+ (snd_rpi_hifiberry_dac)
Reconfiguring Beocreate software
Value could not be interpreted as JSON, falling back to old method.
Settings updated for 'system'.
 updated card type
["pi","bluetooth","pi3orlater","arm7","dsp","toslink","localui"]
Settings updated for 'system'.
Value could not be interpreted as JSON, falling back to old method.
Settings updated for 'system'.
Restarting beocreate2
 restarting Beocreate
```

If I run `/opt/hifiberry/bin/reconfigure-players` **with** a `/etc/hifiberry/config.fixed` I get the right Beocreate sound card, but the DSP disappears:
```
# /etc/hifiberry/config.fixed
MIXER_CONTROL="DSPVolume"
CARD="Beocreate 4-Channel Amplifier"
FEATURES="toslink localui"
```
```
/opt/hifiberry/bin/reconfigure-players: line 50: $N=${CURRENT_$N}: bad substitution
Using fixed card Beocreate 4-Channel Amplifier with fetaures toslink localui bluetooth pi3orlater arm7
Using fixed mixer control DSPVolume
/etc/hifiberry ~
~
Sound card settings have been changed, reconfiguring...
Applying settings:
 Players:  (was )
 Raspberry Pi model: 4
 System name: egli-hifi (was egli-hifi)
 Sound card: Beocreate 4-Channel Amplifier (was DAC+ DSP)
 Interrupt pin for power controller:  (was 2)
 DSP type:  (was DAC+ DSP)
 HW device: card 0 (was card 0)
 ALSA mixer control: DSPVolume (was DSPVolume)
 Recording:  (was )
 Vendor/product  (was  )
 Features: toslink localui bluetooth pi3orlater arm7 localui (was pi bluetooth pi3orlater arm7 dsp toslink localui)

Saving settings to /etc/hifiberry.state
Reconfigure features
Reconfiguring Spotifyd
Reconfiguring Vollibrespot
Reconfiguring Shairport-sync
Reconfiguring Bluetooth
Reconfiguring squeezelite
Reconfiguring MPD
Reconfiguring DLNA
Reconfiguring Mopidy
modidy not installed, ignoring
Reconfigure AudioControl2
 updated interrupt pin
Restarting audiocontrol2
Reconfigure upmpdcli
Reconfigure RAAT
Configuring RAAT server for UUID 78142091-3786-441b-9c55-94a1a9e9e085 on DAC+ (snd_rpi_hifiberry_dac)
Reconfiguring Beocreate software
Value could not be interpreted as JSON, falling back to old method.
Settings updated for 'system'.
 updated card type
["toslink","localui","bluetooth","pi3orlater","arm7","localui"]
Settings updated for 'system'.
Restarting beocreate2
 restarting Beocreate
```

**Comment by hifiberry** [comment]
Can you please post the output of 

/opt/hifiberry/bin/read-hat

**Comment by thefiddler** [comment]
Running `/opt/hifiberry/bin/readhat` prints:
```
/opt/hifiberry/bin/readhat: line 23: /sys/class/i2c-adapter/i2c-/new_device: No such file or directory
```

**Comment by hifiberry** [comment]
This should have been fixed some time ago. Can you test with the latest release?

**Comment by jedie** [comment]
Think i have the same Problem with current 20220826 release!

![image](https://user-images.githubusercontent.com/71315/196961227-39839628-1e5e-42e3-b062-21ef71d6a5b6.png)


```
# /opt/hifiberry/bin/readhat
no vendor:no product
```
I tried without and with `/etc/hifiberry/config.fixed` with:
```
MIXER_CONTROL="DSPVolume"
CARD="Beocreate 4-Channel Amplifier"
FEATURES="toslink localui dsp"
```

![image](https://user-images.githubusercontent.com/71315/196961348-0c7a20f4-1c0b-4ac1-8838-7c26d45cac07.png)
