### ISSUE TITLE
LED on-off / firmware updating?

### ISSUE THREAD

**Issue by ecsedya** [hifiberry/hifiberry-os#305]
**Is your feature request related to a problem? Please describe.**

I am trying to switch the LEDs off as described here: https://forums.raspberrypi.com/viewtopic.php?t=149126
Also, I'd like to update the firmware on the Pi.

**Describe the solution you'd like**

Switch on/off LEDs buttons in the Hifiberry OS web config?
Update Firmware button?

**Describe alternatives you've considered**
As there is no SUDO, no APT-GET either, no LS (really?), and when I am trying to edit /boot/config.txt directly, the file system is read only...

**Additional context**
-

**Comment by hifiberry** [comment]
There is and there will be no apt-get as HiFiBerryOS isn't designed to allow software updates by end users. ls is installed and to edit /boot/config.txt you have just to remount /boot read-write.
