### ISSUE TITLE
mac address error for squeezelite

### ISSUE THREAD

**Issue by jamesholdenmusic** [hifiberry/hifiberry-os#306]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
OS needs to wait for network connection before starting squeezelite, as otherwise squeezelite reports an all-zeroes mac address (which leads to conflicts with multiple players as the logitech media server software identifies players by mac address)

**HiFiBerryOS version**
all

**HiFiBerry sound card**
all

**To Reproduce**
1. set up multiple squeezelite / hifiberry players on your network
2. look in LMS player list, they all have 00:00:00:etc mac addresses, and hence cannot coexist simultaneously

**Expected behavior**
hifiberry os should wait before starting squeezelite, then the squeezelite player will report a correct mac address to the server

**Screenshots**
n/a

**Browser (if applicable)**
n/a

**Additional context**

**Comment by hifiberry** [comment]
Addresses with 9f53175178c9da83d3aca9afc29f74ffc53fa0bf

**Comment by hifiberry** [comment]
This has been implemented in release 20220114
