### ISSUE TITLE
cyclic systemd dependency due to pc-startup and pc-shutdown

### ISSUE THREAD

**Issue by hypnotoad** [hifiberry/hifiberry-os#309]
**Describe the bug**
systemctl --failed lists several failed services: fsck-rort, pc-startup and pc-shutdown. 
journalctl shows that it starts with cyclic dependencies. Disabling all pc-* services solves the dependency problem and the system boots up without systemd dependency errors.

**HiFiBerryOS version**
20210804 and 20211105

**HiFiBerry sound card**
beocreate

**To Reproduce**
ssh root@hifiberry
systemctl --failed

**Expected behavior**
no failed services

**Screenshots**
first error by dmesg:

[    2.205051] systemd[1]: systemd 247 running in system mode. (-PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP -LIBCRYPTSETUP +GCRYPT +GNUTLS -ACL -XZ -LZ4 -ZSTD -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid)
[    2.205895] systemd[1]: Detected architecture arm.
[    2.266018] systemd[1]: Set hostname to <beocreate>.
[    2.684315] systemd[1]: /usr/lib/systemd/system/pc-shutdown.service:8: Unknown key name 'ExecStopPre' in section 'Service', ignoring.
[    2.747855] systemd[1]: /usr/lib/systemd/system/beocreate2.service:18: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
[    2.747914] systemd[1]: /usr/lib/systemd/system/beocreate2.service:19: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
[    2.823707] systemd[1]: sysinit.target: Found ordering cycle on systemd-tmpfiles-setup.service/start
[    2.823794] systemd[1]: sysinit.target: Found dependency on systemd-journald.service/start
[    2.823822] systemd[1]: sysinit.target: Found dependency on pc-startup.service/start
[    2.823849] systemd[1]: sysinit.target: Found dependency on basic.target/start
[    2.823876] systemd[1]: sysinit.target: Found dependency on sysinit.target/start
[    2.823904] systemd[1]: sysinit.target: Job systemd-tmpfiles-setup.service/start deleted to break ordering cycle starting with sysinit.target/start
[    2.824679] systemd[1]: sysinit.target: Found ordering cycle on systemd-journald.service/start
[    2.824706] systemd[1]: sysinit.target: Found dependency on pc-startup.service/start
[    2.824732] systemd[1]: sysinit.target: Found dependency on basic.target/start
[    2.824757] systemd[1]: sysinit.target: Found dependency on sysinit.target/start
[    2.824785] systemd[1]: sysinit.target: Job systemd-journald.service/start deleted to break ordering cycle starting with sysinit.target/start
[    2.827629] systemd[1]: Queued start job for default target Multi-User System.

**Browser (if applicable)**
n/a

**Additional context**
I upgraded the system several times this year.

**Comment by hifiberry** [comment]
This has nothing to do with cyclic dependencies, but with the fact that command that sent to the power controller fail.
We'll fix this in the next release.
