### ISSUE TITLE
iTunes on Windows does not work with Shairport 4 (Airplay 2)

### ISSUE THREAD

**Issue by theblond** [hifiberry/hifiberry-os#311]
**Describe the bug**
Since Hifiberry impelements Shairport version 4 with its Airplay 2 feature, Airplay does not work with iTunes on Windows anymore. They say Airplay 2 is under development with known limitations: [Infos on Airplay 2](https://github.com/mikebrady/shairport-sync/blob/development/AIRPLAY2.md)

**HiFiBerryOS version**
since 20210804

**Expected behavior**
Can you stick to the latest release of shairport (version 3.3.8)  and Airplay 1 until this is fixed?

**Comment by hifiberry** [comment]
As many users prefer Airplay 2, we won't go back to a previous version of Shairport. I recommend to download an older release of HiFiBerryOS and stick with this (disable automatic updates).
