### ISSUE TITLE
Support for a Bidirectional communication API of audiocontrol2

### ISSUE THREAD

**Issue by schnabel** [hifiberry/hifiberry-os#313]
**Is your feature request related to a problem? Please describe.**
hifiberry-os should support socketio, gevent and bottle-websocket to enable a [Bidirectional communication API](https://github.com/hifiberry/audiocontrol2/issues/20)

**Describe the solution you'd like**
Activate the needed packages for a socketio based api of audiocontrol2. (Most packages are part of the buildroot 2021-11 release which is available since last Sunday :-)). For the rest I could offer a PR.

**Describe alternatives you've considered**

**Additional context**

**Comment by hifiberry** [comment]
Please first start with the PR for audiocontrol. I'll have a look at this.
