### ISSUE TITLE
Support for rtl8812au based wifi dongles

### ISSUE THREAD

**Issue by dheckl** [hifiberry/hifiberry-os#320]
Is it possible to add the required drivers for rtl8812au based wifi dongles to the build? Buildroot has a config parameter to add the required drivers: https://github.com/buildroot/buildroot/blob/b4c76008fcbb7a183e19d6c6fe06f28e63b64cbd/package/rtl8812au-aircrack-ng/Config.in

I would appreciate to have the driver inside the official build, so a lot of modern wifi dongles would be supported.

**Comment by hifiberry** [comment]
That wouldn't help as it would also require the whole configuration for the adapter which isn't implemented at all. This would require some more work. If somebody wants to implement this and provide a pull request, we're happy to look into it.
