### ISSUE TITLE
Add support for usb ethernet adapters

### ISSUE THREAD

**Issue by noranraskin** [hifiberry/hifiberry-os#322]
**Is your feature request related to a problem? Please describe.**
Adding support for usb network interfaces would make working with the pi zero and pi zero 2 much easier. Also, I've had the onboard network interface die on me once, it would be great to just have the flexibility.

**Describe the solution you'd like**
Adding support for usb ethernet.

**Describe alternatives you've considered**
For the pi zero and zero 2 there isn't really an alternative if you want a wired internet connection.

**Additional context**
-

**Comment by hifiberry** [comment]
As the Pi Zero isn't really a preferred platform for us, there will be no work on this from us. However, we're willing to look into pull requests if somebody wants to work on this.
