### ISSUE TITLE
Lost connection from Spotify  (Pi4)

### ISSUE THREAD

**Issue by IlkAta** [hifiberry/hifiberry-os#325]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
Recently I lost the connection to HiFiBerry (running on Pi4) from Spotify.  I have to restart both HiFiBerry and Spotify to get connection.  Restarting both HiFiBerry and Spotify fixes the issue temporarily.

**HiFiBerryOS version**
20211105

**HiFiBerry sound card**
DAC+ ADC Pro

**To Reproduce**
1. In Spotify when I click on "connect to device" the HiFiBerry is not visable

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/97064041/147981735-11571eba-a206-44cf-bac6-fad9486d4852.png)

**Browser (if applicable)**

**Additional context**
Network connection via ethernet cable
audiocontrol2, beocreate2, bluetooth, bluealsa, bluealsa-aplay, mpd, pigpio, shairport-sync, sigmatcp, spotify, sshd and ympd running.

[hifiberry-debug.zip](https://github.com/hifiberry/hifiberry-os/files/7804060/hifiberry-debug.zip)

**Comment by tompeel** [comment]
I second this but with a slightly different symptom in the Spotify app.
![image](https://user-images.githubusercontent.com/6130043/148814703-31aca7b0-87df-42eb-bae8-eb29275d4dd7.png)
All the same versions but I'm using the beocreate

**Comment by hifiberry** [comment]
Works just fine here. Unfortunately, there is nothing we can really do here. You might check in our community area. Maybe some other user can give you a tip what might cause this.
