### ISSUE TITLE
High CPU usage when "connected display" option is activated

### ISSUE THREAD

**Issue by schmurtzm** [hifiberry/hifiberry-os#328]
**Describe the bug**
On Rpi 3B : High CPU usage when "connected display" option is activated.
This process use a lot of CPU :
/usr/libexec/wpe-webkit-1.0/WPEWebProcess

Also I feel the web UI laggy on local screen (and not at all remotely).

**HiFiBerryOS version**
20211105

**HiFiBerry sound card**
HiFiBerry DAC+ standard – RCA version

**To Reproduce**
1. Activate option "Use Connected Display"
2. wait some hours (it's not immediate after activating)
3. check cpu consumption, it should be high (even if nothing is playing and screensaver disabled)
4. the cpu consumption return to normal if you disable "Use Connected Display"

**Expected behavior**
Few CPU consumption when idle

**Screenshots**
![image](https://user-images.githubusercontent.com/7110113/150618628-e79676d5-2314-4e03-870f-8dda5bfbe4d7.png)

**Browser (if applicable)**

**Additional context**

**Comment by hifiberry** [comment]
That's the web browser process that handles the local UI. As long as no better web browser is available, that's just normal.
