### ISSUE TITLE
Only left or only right speaker

### ISSUE THREAD

**Issue by sweenu** [hifiberry/hifiberry-os#342]
**Is your feature request related to a problem? Please describe.**
I have two speakers attached, both to their own Amp2 with HifiberryOS. I am not able to do stereo with them because they're not connected to the same Amp2

**Describe the solution you'd like**
I'd like more options that just stereo or mono, I'd like a way to balance between channels and more specifically, in my case, tell one of the speaker to act as the left speaker and the other as right speaker.

**Comment by npmstart-pray** [comment]
May I suggest that this project may be more suitable?  https://github.com/balenalabs/balena-sound

**Comment by sweenu** [comment]
That looks very cool, I'll look into that! It's based on snapcast which is the source I use in HifiberryOS.

**Comment by npmstart-pray** [comment]
It may be the solution you’re looking for, to sync 2 Pi Nodes over a network. 
if you want one channel of audio in one location and the other in a separate one, they make this stuff called speaker cable that’s pretty inexpensive and I personally think is pretty neat, but I know it doesn’t work in every application ;)
