### ISSUE TITLE
Adding the ability to add startup parameters for Squeezelite in HifiberryOS

### ISSUE THREAD

**Issue by gjomle** [hifiberry/hifiberry-os#348]
I would like to have the ability to add startup parameters to Squeezelite in HifiberryOS. Perhaps add an input field in the advanced option of the Squeezelite settings.

The reason for this (for my spesific situation) is that my dac only supports 96khz.

My option is to install PiCorePlayer or Max2Play (which have this ability), but I really like the GUI for the DSP card and would like to stick with HifiberryOS.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hifiberry** [comment]
I'm sorry, but we definitely won't add this to the UI. Doing this would mean HBOS end up like many other distributions will all kinds of settings in the UI that no normal user understands. If you want to create a PULL request to add some options on the command line level, feel free to do so.
