### ISSUE TITLE
No new releases

### ISSUE THREAD

**Issue by dgomes** [hifiberry/hifiberry-os#350]
**Describe the bug**
Running 20211105 on a RPi3 with no issues up to now.
Realised there were more recent releases that have not reached my RPi3
"Automatic Updates" are set to quick

**HiFiBerryOS version**
20211105

**HiFiBerry sound card**
"DAC+"

**To Reproduce**
1. Go to 'Software Update'
2. Check current version

**Expected behavior**
I expected to see upgrade options to a more recent release 2022*

**Comment by hifiberry** [comment]
That just normal as there has been a problem with this release and we had to stop distribution.

**Comment by dgomes** [comment]
So it's remove the SD card and start over ?

**Comment by hifiberry** [comment]
Just do nothing if your system works.

**Comment by dgomes** [comment]
Airplay doesn't :(

**Comment by hifiberry** [comment]
Just use an older release.

**Comment by npmstart-pray** [comment]
Wait - the current release from last week broke AirPlay? V20220223 I think?
