### ISSUE TITLE
No trigger and action items under the interact setting

### ISSUE THREAD

**Issue by cfhsu** [hifiberry/hifiberry-os#352]
**Describe the bug**
No trigger and action items under the interact setting.

**HiFiBerryOS version**
20220228

**HiFiBerry sound card**
DAC+ DAC

**To Reproduce**
1. Go to 'INTERACT'
2. Click on 'NEW INTERACTION'
3. Click on 'CHOOSE TRIGGER' and 'ADD ACTION'
4. See nothing showing up

**Expected behavior**
A list of different triggers and actions to choose from

**Screenshots**

**Browser (if applicable)**
 - OS: iOS 15.3.1 and Windows 10
 - Browser: chrome, safari
 - Version:  98.0.4758.102

**Additional context**
Using Raspberry Pi 3B+ and this has been a problem since last update in Feb.

**Comment by Thornild2** [comment]
I have the same problem

**Comment by dodepier** [comment]
Me to 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/33546352/157042619-44363f8d-3e2f-4863-b806-e5490ba8ff97.png">


<img width="286" alt="image" src="https://user-images.githubusercontent.com/33546352/157042740-aa06b477-486c-46a8-b3ab-66ca0ebeed1b.png">

**Comment by borky** [comment]
Same for me with the latest version. Downgraded to previous version and the triggers/actions become again available.

**Comment by dvandeijl** [comment]
In addition my Arduino microcontroller also not present in the serial port menu:
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/63461262/159577479-42a650c0-eea3-48cd-bdf3-eacc21cb0d62.png">

**Comment by escoand** [comment]
Same problem here.

**Comment by escoand** [comment]
@borkog and is changing it back working?

**Comment by borkog** [comment]
No … restoring old OS did

**Comment by escoand** [comment]
Is it maybe a similar reason as #359?

**Comment by borkog** [comment]
It doesn't work on a clean install ...

**Comment by borkog** [comment]
forgot to tell... it's rp3 and amp2 (1.1)

**Comment by dodepier** [comment]
@hifiberry When is the next release? A small bug fix on current version would also be great.

**Comment by hifiberry** [comment]
We can't simply do a "small bug fix" on the current release as we always need to build a new release.
We expect a new release in the next 1-2 weeks.

**Comment by dodepier** [comment]
@hifiberry what is the status of the next release? I see that the bug is fix in the development branch.
