### ISSUE TITLE
Wifi channel 13 not available

### ISSUE THREAD

**Issue by sebastianrothe** [hifiberry/hifiberry-os#354]
Thanks for the nice products and this distribution.

I updated my PI3 to 2022028 recently, which broke my wifi connection. In Germany, we have additional channels (12, 13). But even after setting the country code in the UI and seeing it in /etc/wpa_supplicant the PI won't find the networks. It seems the channels are not scanned. I tried with iwlist, iwconfig and wpa_cli, which gives the same result.

It worked with 20211105.

**Comment by theblond** [comment]
It was a bug in kernel 5.15 and has been already fixed:
https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/217#issuecomment-1084875159

**Comment by sebastianrothe** [comment]
> It was a bug in kernel 5.15 and has been already fixed: [raspberrypi/Raspberry-Pi-OS-64bit#217 (comment)](https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/217#issuecomment-1084875159)
Thanks for the follow-up 👍

**Comment by hifiberry** [comment]
We'll upgrade the kernel to the latest version in the next release

**Comment by sebastianrothe** [comment]
Thanks

**Comment by sebastianrothe** [comment]
Has been fixed with https://github.com/hifiberry/hifiberry-os/releases/tag/v20220726

Thanks!
