### ISSUE TITLE
Pi Zero W build has broken spotify

### ISSUE THREAD

**Issue by camielverdult** [hifiberry/hifiberry-os#356]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**

**HiFiBerryOS version**
Pi Zero W build has broken spotify

**HiFiBerry sound card**
HifiBerry DAC+ HW 2.6

**To Reproduce**
1. Make SD card with Hifiberry OS for Pi zero W.
2. Boot up SD Card.
3. Wait.
4. Connect to hifiberry wifi
5. Connect hifiberry to hifi
6. Try spotify connect

**Expected behavior**
Hifiberry in spotify connect list

**Additional context**
Bluetooth does work

**Comment by hifiberry** [comment]
There is no Spotify support on the Pi Zero.
