### ISSUE TITLE
shairport-sync failing to start after renaming device in web interface

### ISSUE THREAD

**Issue by sorig** [hifiberry/hifiberry-os#359]
**Describe the bug**
Whenever I tried enabling airplay in the web interface, it would immediately return to the disabled list. Airplay was not working. I have identified the fix and am only posting here to report this bug to the developers.

**HiFiBerryOS version**
20220228

**HiFiBerry sound card**
DAC2 HD

**To Reproduce**
1. Flash the latest hifiberry-os onto the microsd card
2. Connect the pi to the router via cable to run the setup wizard
3. Configure wifi, unplug the LAN cable, and restart with WiFi connection
4. Enable DLNA
5. Update hifiberry to latest version
6. Change the device name
7. After restarting, airplay is now disabled and cannot be enabled

**Expected behavior**
Airplay should never have been disabled, and you should be able to enable airplay.

**Screenshots**
N/A

**Browser (if applicable)**
 - OS: Fedora 35
 - Browser Firefox
 - Version 98.0

**Additional context**
I ssh'ed into the pi to check what was going on. systemctl was saying that the shairport-sync service was exiting with code 11 (segfault) and kept trying to restart it. I had a look at `/etc/shairport-sync.conf` which contained:

```
general =
{
	name = "My hifiberry";
}
alsa =
{
	mixer_control_name = "DAC";
}
sessioncontrol =
{
	run_this_before_play_begins = "/opt/hifiberry/bin/pause-all shairport";
	wait_for_completion = "NaN";
	allow_session_interruption = "yes";
	session_timeout = 20;
}

```

I changed: `wait_for_completion = "NaN";` to `wait_for_completion = "yes";` and restarted the service with 
```
systemctl restart shairport-sync
```
And everything now works as expected.

So I conclude that you must have a bug somewhere that writes the invalid `"NaN"` value to the `"wait_for_completion"` field when the device is renamed.

**Comment by hifiberry** [comment]
Tested several scenarios. It seems to be fixed in the latest development version.
