### ISSUE TITLE
gpio-poweroff does not work anymore

### ISSUE THREAD

**Issue by borkog** [hifiberry/hifiberry-os#361]
**Describe the bug**

**gpio-poweroff** this does not work for some reason... It used to before

dtoverlay=gpio-poweroff,gpiopin=26,active_low="y"

**HiFiBerryOS version**
20211105

**HiFiBerry sound card**
Amp2

**To Reproduce**
1.  added line 
dtoverlay=gpio-poweroff,gpiopin=26,active_low="y"
to /boot/config.txt

**Expected behavior**
GPIO 26 should go high when RPI works

**Comment by pinballpower** [comment]
This is not a bug as it was never supported. Feel free to debug it by yourself and post your findings here. However, we won't look into this.

**Comment by hifiberry** [comment]
This is not a bug as it was never supported. Feel free to debug it by yourself and post your findings here. However, we won't look into this.
