### ISSUE TITLE
Unable to compile Hifiberry OS - ERROR: architecture for node module is "Advanced Micro Devices X86-64", should be "ARM"

### ISSUE THREAD

**Issue by admsm** [hifiberry/hifiberry-os#363]
**Describe the bug**
Unable to compile Hifiberry OS. Following steps in Setup Dev Env https://github.com/hifiberry/hifiberry-os/blob/master/doc/setupdev.md. Getting below error:
+ eventemitter3@4.0.7
+ node-fetch@2.6.2
+ express@4.18.0
+ websocket@1.0.34
+ country-list@2.2.0
+ request@2.88.2
+ underscore@1.13.3
+ xml-js@1.6.11
+ wireless-tools@0.19.0
+ node-cec@0.1.2
+ jimp@0.16.1
+ mpd-api@1.1.0
+ pigpio@3.3.1
+ onoff@6.0.3
+ dnssd2@1.0.0
+ node-tunein-radio@0.3.4
+ serialport@10.4.0
+ node-hid@2.1.1
+ aplay@1.2.0
added 337 packages from 378 contributors in 46.666s
ERROR: architecture for "/usr/lib/node_modules/websocket/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node" is "Advanced Micro Devices X86-64", should be "ARM"
ERROR: architecture for "/usr/lib/node_modules/websocket/node_modules/bufferutil/prebuilds/linux-x64/node.napi.node" is "Advanced Micro Devices X86-64", should be "ARM"
ERROR: architecture for "/usr/lib/node_modules/serialport/node_modules/@serialport/bindings-cpp/prebuilds/android-arm64/node.napi.armv8.node" is "AArch64", should be "ARM"
ERROR: architecture for "/usr/lib/node_modules/serialport/node_modules/@serialport/bindings-cpp/prebuilds/linux-arm64/node.napi.armv8.node" is "AArch64", should be "ARM"
ERROR: architecture for "/usr/lib/node_modules/serialport/node_modules/@serialport/bindings-cpp/prebuilds/linux-x64/node.napi.glibc.node" is "Advanced Micro Devices X86-64", should be "ARM"
ERROR: architecture for "/usr/lib/node_modules/serialport/node_modules/@serialport/bindings-cpp/prebuilds/linux-x64/node.napi.musl.node" is "Advanced Micro Devices X86-64", should be "ARM"
make[1]: *** [package/pkg-generic.mk:408: /home/anupam/buildroot-4/build/nodejs-14.18.1/.stamp_installed] Error 1
make: *** [Makefile:84: _all] Error 2

**HiFiBerryOS version**
Compile steps is failing.

**HiFiBerry sound card**
Compile steps is failing.

**To Reproduce**
Following steps in below document to create an image for Pi-4.
https://github.com/hifiberry/hifiberry-os/blob/master/doc/setupdev.md

**Expected behavior**
sdcard image in /buildroot-4/images

**Screenshots**

**Browser (if applicable)**
 - OS: 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

**Additional context**
Haven't made any changes. Worked for couple of times and then start to fail. Have already tried 4-5 times. Fails if i do a full compile or specific packages e.g. ./compile 4 hifiberry
Have also tried removing all Hifiberry, buildroot folders from the machine and starting from scratch.

**Comment by hifiberry** [comment]
That's normal, just run compile again.
