### ISSUE TITLE
Display optical in/out sampling rate

### ISSUE THREAD

**Issue by hajameLin** [hifiberry/hifiberry-os#368]
**Is your feature request related to a problem? Please describe.**
Do not know what sampling rate does the source run and whether the DSP has altered the sampling rate for DAC input.

**Describe the solution you'd like**
Display optical input and output sampling rates.

**Describe alternatives you've considered**
If input sampling rate display is not possible, show output sampling rate only.

**Additional context**

**Comment by hifiberry** [comment]
There are no plans for this. It was our decision to not deal with non-music relates information like file names, sample formats, sample rates etc. in the UI. 
You might create your own patch, but we don't plan to integrate this in the normal HiFIBerryOS release.
