### ISSUE TITLE
WiFi access point

### ISSUE THREAD

**Issue by x838nwy** [hifiberry/hifiberry-os#37]
I know using a wired connection is preferred, but just want to let you know what I'm seeing.

Without a wired connection, the boot sequence ends with "No network connected, configure network using wifi setup." Which is usual.

Unfortunately, the unit then does not emit any wifi signal for me to connect to.

This is a clean install and 2 microSD cards, same results. I tried running Rapsbian and wifi works fine.

Thanks

C

**Comment by hifiberry** [comment]
Hi,

problem is that we can't debug it without network access as we don't know what's going on. Try connecting it to Ethernet network, then check if it connects to your wireless network.

Best regards,
Daniel

**Comment by x838nwy** [comment]
Tried it (wired then connect it to the wifi network). Seems to work fine.
Got an IP address and everything.

**Comment by hifiberry** [comment]
So that means you just the access point isn't starting. Unfortunately I don't really know how to debug this at the moment. 
Let's wait for the February release that should be ready next week and see if this changes something (even if there is no known bugfix for this included)

**Comment by hifiberry** [comment]
Could you do y test with the February release already?

**Comment by x838nwy** [comment]
Hi - super sorry but I'm away from home right now. From what I understand,
it's pretty stable after just a normal update. I'll be able to do this
later next week.

**Comment by hifiberry** [comment]
March release is out now. Can you test this one?
