### ISSUE TITLE
Folder view for music library

### ISSUE THREAD

**Issue by Franky1265** [hifiberry/hifiberry-os#373]
**Is your feature request related to a problem? Please describe.**
Feature Request
My problem is that i do not find all my music, as the artist is not matched, or there is no album. 

**Describe the solution you'd like**
I would like to have a folder view for my music library

Unfortunately my mp3 files are not all tagged right
So not all tiltles are seen in the library
I arranged my files all in folders on my NAS 
So i would love to get ths

 Regards Frank

**Comment by hifiberry** [comment]
We don't plan this as the whole idea of HiFiBerryOS is to focus on music, not files, file formats and other stuff. 
Have a look here for tools that can help you tagging your music:
https://www.hifiberry.com/blog/tools-to-tag-your-music-collection/
