### ISSUE TITLE
Add option to disable on-board LED

### ISSUE THREAD

**Issue by goldenegg** [hifiberry/hifiberry-os#378]
**Is your feature request related to a problem? Please describe.**
Provide an option to turn off the LED on the RPi.

**Describe the solution you'd like**
An option can be added in the settings, allowing the user to disable the on-board LED. This option exists in RoPiee.

**Describe alternatives you've considered**
Taping over the LED is the only other real option, but not preferred.

**Additional context**
Nothing more to add.

**Comment by LopeKinz** [comment]
solder the led out. better solution 🤷‍♀️

**Comment by grischard** [comment]
https://mlagerberg.gitbooks.io/raspberry-pi/content/5.2-leds.html describes how to control the LEDs, including a way of disabling them permanently. Note that the changes to /boot/config.txt need to be re-done after an update.

```bash
mount -o remount,rw /boot
# cat >> /boot/config.txt << EOF
dtparam=act_led_trigger=none
dtparam=act_led_activelow=off
dtparam=pwr_led_trigger=none
dtparam=pwr_led_activelow=off
EOF
```
