### ISSUE TITLE
Show RPi CPU temp in web UI

### ISSUE THREAD

**Issue by goldenegg** [hifiberry/hifiberry-os#379]
**Is your feature request related to a problem? Please describe.**
To ensure the RPi is not over heating, it would be great to have the CPU temp displayed somewhere in the web UI.

**Describe the solution you'd like**
Somewhere in the web UI, display the temp. It could be placed in the diagnostics information section, but I'd personally prefer if it was more easily accessible.

**Describe alternatives you've considered**
No alternatives are available.

**Additional context**
Nothing to add.

**Comment by hifiberry** [comment]
HiFiBerryOS is about music, therefore we won't display technical parameters in the UI. 
As the Pi's CPU just throttles if it get's too hot, there is no need to monitor this temperature.
