### ISSUE TITLE
MDP not launching from xxx.local

### ISSUE THREAD

**Issue by jwrw** [hifiberry/hifiberry-os#38]
Open the interface using http://xxx.local (xxx=<whatever you've called your 'berry) and open up the MDP page from the Sources page.

Click the 'OPEN MDP WEB PAGE' button and it fails to load - on Safari get 'Safari can't open the page xxx.local:9000 because the server unexpectedly dropped the connection.'  Other browsers are similar.

Opening the interface using an IP address e.g. 192.168.1.99 and follow the above steps and MDP page opens just fine.

NB. Browsing directly to http://xxx.local:9000 gives the same error so it's probably an mDNS thing???

**Comment by hifiberry** [comment]
Yes, it's probably an mDNS thing. Unfortunately these are really hard to debug remotely :(
As you're using Safari, you probably use MacOS - right?

**Comment by jwrw** [comment]
Yes, this was on MacOS.  Couldn't get xxx.local working at all from a Windows 10 device - but didn't try very hard.  I did run the 'Discovery' app which shows the services that are being advertised.  There's sftp and ssh (which corresponds to the static set-up I can see on the RasPi) and a couple of other services that must be added in a more dynamic way??  I'll attach a screen grab if that would be useful.

**Comment by hifiberry** [comment]
The browser should work just with name resolution, but we can try if advertising HTTP services might improve this.

**Comment by jwrw** [comment]
I'd agree - I was a little perplexed myself as by my understanding it should work OK.

**Comment by hifiberry** [comment]
Do oyu have another Linux system (even a VM would be fine) around?

Try 
avahi-resolve -n xxx.local

**Comment by hifiberry** [comment]
Another idea: does your hostname contain uppercase letters?

**Comment by jwrw** [comment]
Tried curl http://xxx.local which worked OK when using the browser didn't.  Did a wireshark and I think it's a IPv6 vs IPv4 thing.  curl uses IPv4 (which works), the browser is trying to do IPv6 and the server drops the connection. So looks like the mdp web server is not doing IPv6 - although mDNS is sending back V4 and V6 responses from the berry.

**Comment by hifiberry** [comment]
Good observation. I'll see if there is a chance to have this working at IPv6.

**Comment by hifiberry** [comment]
Can you try the following:

- Login via SSH
- Edit /usr/lib/systemd/system/ympd.service
  Change the ExecStart line to
     ExecStart=/usr/bin/ympd -w "[::]:9000"
- systemctl daemon-reload
- systemctl restart ympd

**Comment by jwrw** [comment]
Yeah! That's done the trick. Working OK with Safari and Chrome on Mac.  Also "curl -4" and "curl -6" both work OK.  One day I will get my head around IPv6!

**Comment by hifiberry** [comment]
Great. We'll integrate this in the next release.

**Comment by hifiberry** [comment]
This is integrated into our 20200226 release now. Can you try upgrading?

**Comment by jwrw** [comment]
Upgrade all OK.  Launching MPD is fine from the GUI with Safari & Chrome on Mac. Seems OK to close?

**Comment by hifiberry** [comment]
Thanks for you help with this.
