### ISSUE TITLE
The keyboard has no # symbol

### ISSUE THREAD

**Issue by dflvunoooooo** [hifiberry/hifiberry-os#389]
**Describe the bug**
The virtual keyboard has no # symbol.

**HiFiBerryOS version**
No idea, I can not boot, because I can not connect to my wifi, because of the missing #.

**HiFiBerry sound card**
amp2

**To Reproduce**
Flash sd.
Boot.
Type something with the virtual keyboard, thats got a # in it.

**Expected behavior**
I expect a keyboard to have the # symbol.

**Screenshots**
![PXL_20220908_154827946 MV](https://user-images.githubusercontent.com/32816598/189167794-6282fcf8-8c03-4fd2-bf10-215eb971f761.jpg)
![PXL_20220908_154833800 MV](https://user-images.githubusercontent.com/32816598/189167826-5321e62e-8cb3-4a3d-b329-cad9ba2fa681.jpg)

**Browser (if applicable)**
None

**Additional context**
There is none needed in my opinion.

**Comment by hifiberry** [comment]
You can just connect it via Ethernet and configure via a remote web browser,
