### ISSUE TITLE
Cannot pick latest fw 20221109

### ISSUE THREAD

**Issue by lucasso72** [hifiberry/hifiberry-os#400]
**Describe the bug**
Either via webUI or CLI cannot pick up latest firmware.

**HiFiBerryOS version**
20221026

**HiFiBerry sound card**
DAC+ Pro

**To Reproduce**
1. 
2. 
3. 
4.

**Expected behavior**
Latest 20221109

**Screenshots**
![image](https://user-images.githubusercontent.com/18735915/201202573-93fe8b96-1c8b-4b8d-9f20-40706e95fa3f.jpeg)

![image](https://user-images.githubusercontent.com/18735915/201202603-70132a70-2175-4de1-9ec6-ddbbdf5bf771.jpeg)

**Browser (if applicable)**
 - OS: any
 - Browser any
 - Version any

**Additional context**

**Comment by hifiberry** [comment]
This has not yet been released for an upgrade in the applictaion. It's still experimental.
