### ISSUE TITLE
Zeroconf (Avahi) name resolution fails for the local network because it resolves to the docker0 interface address

### ISSUE THREAD

**Issue by jjboor** [hifiberry/hifiberry-os#401]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
When trying to reach the hifiberry web interface name resolution failed. It turned out the avahi-daemon in hifiberry resolved the hostname to the docker0 interface address (172.17.x.x) making it unreachable for the network on wlan0 on my setup (10.10.x.x). 

**HiFiBerryOS version**
System software 20220826

**HiFiBerry sound card**
DAC+ ADC Pro

**To Reproduce**
This is not easy to reproduce as it seem to happen after a normal reboot/startup

**Expected behavior**
The system should resolve the (host)name set in the Web interface always to either the wired (eth0) or wireless (wlan0) interfaces

**Screenshots**

**Browser (if applicable)**

**Additional context**
An easy fix that works for me is to set deny-interfaces=docker0 in /etc/avahi/avahi-daemon.conf

**Comment by hifiberry** [comment]
This will be fixed in the next HBOS64 release.
