### ISSUE TITLE
Can hifiberry-os play CD's?

### ISSUE THREAD

**Issue by zjDrummond** [hifiberry/hifiberry-os#406]
**Is your feature request related to a problem? Please describe.**
CD players are bulky, and expensive. USB optical drives are affordable, and small. 

**Describe the solution you'd like**
It would be cool to be able to connect a optical drive to the raspberry pi via USB, and play audio CD's. 

**Describe alternatives you've considered**
I have seen volumio has a payed pluggin to do this, but paying for CD playback is kinda silly. Tons of open source apps can playback CD's in linux. There's nothing magic about it. It's a standard dating back decades. 

**Additional context**
Just think about all the budget hifi nerds who would love this. You could forego the purchase of an expensive CD player if you already have a pi with a hifiberry DAC. One device to play your music library both physical and digital. :)

**Comment by hifiberry** [comment]
There are no plans from us to implement this. Ripping CDs is quite easy today and just using the files is already possible. However, we're open for contributions. The best way is probably to create a docker container with this functionality.
