### ISSUE TITLE
20221128 doesn't work on Beocreate

### ISSUE THREAD

**Issue by schwachstelle** [hifiberry/hifiberry-os#407]
**Describe the bug**
20221128 doesn't work on Beocreate: no sound output because the DSP cannot be accessed

**HiFiBerryOS version**
20221128

**HiFiBerry sound card**
Beocreate

**To Reproduce**
1. update to 20221128
2. go to sound/DSP programs
3. see message: "There is a problem accessing the sound processor (not responding)."
4. thus, sound doesn't play

**Expected behavior**
sound processor can be accessed and sound is playing

**Screenshots**
![Screenshot_20221128-192356](https://user-images.githubusercontent.com/73094558/204504811-a921d068-8ac3-411c-a561-22b6e5196b84.png)

**Browser (if applicable)**
doesn't matter

**Additional context**
downgrading to 20221026 fixes the problem

**Comment by hifiberry** [comment]
I'm sorry for the late reply. I can't reproduce this here. What version of the Beocreate amplifier are you using?

**Comment by schwachstelle** [comment]
No worries.  :-)  It's a Beocreate 2.4.4 in combination with a Pi 4.

**Comment by schwachstelle** [comment]
Any news on this issue?

Btw: how do I determine the version of the board? I just picked up the version info from the main web ui page. But it shows 2.4.4 for my AMP3 + DSP as well...

**Comment by hifiberry** [comment]
Do you still see this with the latest release?

**Comment by schwachstelle** [comment]
No, 20230404 fixes this problem. Thanks for the fix!  :-)
