### ISSUE TITLE
HBOS 20221128 AMP3 PI3B no sound - some clicking

### ISSUE THREAD

**Issue by Boltzmann** [hifiberry/hifiberry-os#408]
**Describe the bug**
Playing mp3s or test sounds with
```
# play -n synth sine 1000
play WARN alsa: can't encode 0-bit Unknown or not applicable
 File Size: 0         
  Encoding: n/a           
  Channels: 1 @ 32-bit   
Samplerate: 48000Hz      
Replaygain: off         
  Duration: unknown 
```
gives only some clicks but no sound.
**HiFiBerryOS version**
20221128
**HiFiBerry sound card**
AMP3 on Raspberry Pi 3 Model B Rev 1.2

**To Reproduce**
1. Install new hifiberryos image on sd card.
2. Start Raspberry with AMP3 attached.
3. Configure it - name ... nothing special, a USB stick with music is attached.
4. Play some local music.

**Expected behavior**
Hearing some music that was selected. 

**Screenshots**
Maybe later if not clear. It is rather the sound...

**Browser (if applicable)**
 - OS: Debian buster
 - Browser Firefox
 - Version 107.0.1
 - ...however, have this in the webUI, when playing songs and also when using `aplay 14\ Streets\ Of\ Philadelphia.mp3` or the test sound (see top)

**Additional context**
The AMP3 is pretty new, the hifiberryos is a fresh install.

**Comment by hifiberry** [comment]
We can't reproduce this here. 

What's the output of

aplay -l

**Comment by Boltzmann** [comment]
Thank you for the answer and try. Here is the output
```
# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_amp3], device 0: Hifiberry Amp3 ma120x0p-amp-0 [Hifiberry Amp3 ma120x0p-amp-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by powertim** [comment]
Hi @Boltzmann , have you check that cables are not touching ? I had same issue here + inverted the polarities on channels.

**Comment by Boltzmann** [comment]
Will check this weekend.

**Comment by Boltzmann** [comment]
The cables do not touch. I switched the polarity of the cables - nothing new.

**Comment by Boltzmann** [comment]
I have here several speakers. It is always the same phenomenon: No sound. 

I bought this as a replacement for a Hifiberry Amp+ 1 that produced only white noise or no noise the other day on the same Raspberry Pi 3 Model B Rev 1.2. Because the HifiberryOS is booting fine, a raspberry hardware issue is unlikely. Is it?

**Comment by Boltzmann** [comment]
OK, tried the Hifiberry on another Raspberry Board. The Hifiberry works there with HifiberryOS and Debian 10. Though seems, there is a hardware issue with the Raspberry.
