### ISSUE TITLE
Build fails due to missing (make) jobserver

### ISSUE THREAD

**Issue by hcc23** [hifiberry/hifiberry-os#410]
**Describe the bug**
I cannot locally build hifiberry OS due to some apparently missing make-related _jobserver_.
As the triggering unit (_csu_) seems to being a core GNU element I doubt that the bug is related to their makefile and hence was thinking that the hifiberry-specific build system is hence somewhat broken.

Please note that I am experiencing this bug under _openSUSE_. As I am not using Ubuntu I cannot check if that might be the source of the problem. (

**HiFiBerryOS version**
Current `master` branch (as of PR #403)

**HiFiBerry sound card**
Post the exact type, e.g. DAC+ Pro instead of "DAC+".

**To Reproduce**
1. clone the git repository and `cd` into it
2. **skipping** `prepare-software` as it won't work on non-Debian systems
3. `./get-buildroot`
4. `./build-release 0w` (or any other version for that matter)
5. See error (generated from triggering `compile` manually):

```
❯ ./compile 0w
Secrets file not found, this isn't an official HiFiBerry build
some components might not work as expected
Building in /home/claus/git/buildroot-0w
  GEN     /home/claus/git/buildroot-0w/Makefile
#
# configuration written to /home/claus/git/buildroot-0w/.config
#
Using standard (non package-parallel) build system
/usr/bin/make -j1 O=/home/claus/git/buildroot-0w HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" syncconfig
make[1]: Entering directory '/home/claus/git/buildroot-2021.11'
  GEN     /home/claus/git/buildroot-0w/Makefile
make[1]: Leaving directory '/home/claus/git/buildroot-2021.11'
>>> glibc 2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4 Building
PATH="/home/claus/git/buildroot-0w/host/bin:/home/claus/git/buildroot-0w/host/sbin:/home/claus/.local/bin:/usr/local/bin:/usr/bin:/bin"  /usr/bin/make -j16  -C /home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4/build
make[1]: Entering directory '/home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4/build'
/usr/bin/make -r PARALLELMFLAGS="" -C /home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4 objdir=`pwd` all
make[2]: Entering directory '/home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4'

type "make help" for help with common glibc makefile targets

/usr/bin/make  subdir=csu -C csu ..=../ subdir_lib
make[3]: Entering directory '/home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4/csu'
make[3]: *** Cannot open jobserver /tmp/GMfifo19229r: No such file or directory.  Stop.
make[3]: Leaving directory '/home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4/csu'
make[2]: *** [Makefile:478: csu/subdir_lib] Error 2
make[2]: Leaving directory '/home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4'
make[1]: *** [Makefile:9: all] Error 2
make[1]: Leaving directory '/home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4/build'
make: *** [package/pkg-generic.mk:295: /home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4/.stamp_built] Error 2
```

To me the relevant part seems to be:

````
/usr/bin/make  subdir=csu -C csu ..=../ subdir_lib
make[3]: Entering directory '/home/claus/git/buildroot-0w/build/glibc-2.34-9-g9acab0bba6a5a57323b1f94bf95b21618a9e5aa4/csu'
make[3]: *** Cannot open jobserver /tmp/GMfifo19229r: No such file or directory.  Stop.
````

**Expected behavior**
A ready-to-flash image in the `image` folder

**Screenshots**
_(not applicable)_

**Browser (if applicable)**
 - OS: opensuse tumbleweed (uname -r: 6.1.1-1-default)

**Additional context**
I tried to manually trigger a parallel built (via hardcoding `PARALLEL=1` in the `compile` script) but got the same result.

**Comment by hifiberry** [comment]
The build is designed to work on Ubuntu. I haven't seen this error on Ubuntu. As you also skipped the prepare-software, your distribution might be missing a lot of required packages. 

Build system is designed to work on the latest Ubuntu LTS.
