### ISSUE TITLE
Remote accessing HiFiBerry with VNC

### ISSUE THREAD

**Issue by HoogendoornJH** [hifiberry/hifiberry-os#411]
**Is your feature request related to a problem? Please describe.**
I want to access HiFiBerry remotely with VNC from my Windows computer.

**Describe the solution you'd like**
Implementing VNC in HiFiBerry.

**Describe alternatives you've considered**
Accessing HiFiBerry remotely with ssh, however, this is not graphical.

**Additional context**
None.

**Comment by pinballpower** [comment]
There is no "graphical" interface on the Pi. If you want to access the GUI, just use the web browser.

**Comment by hifiberry** [comment]
There is no "graphical" interface on the Pi. If you want to access the GUI, just use the web browser.

**Comment by HoogendoornJH** [comment]
Ah yes, that works. Sorry, I didn't know that. Thanks for the tip.
