### ISSUE TITLE
spotifyd error : spotifyd: /lib/libasound.so.2: no version information available (required by spotifyd)

### ISSUE THREAD

**Issue by rhe-ch** [hifiberry/hifiberry-os#43]
This error happens when the user tries several times to configure spotify source with release 25.02.2020 because /etc/spotifyd.conf  is appended at each trial instead of been replaced.

To resolve : remove the file /etc/spotifyd.conf and configure it again through the standard page

Log :
spotifyd: /lib/libasound.so.2: no version information available (required by spotifyd)
spotifyd: /lib/libasound.so.2: no version information available (required by spotifyd)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("duplicate field `global`")', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by hifiberry** [comment]
Thanks for reporting it. It had been fixed already todayy. Try the 20200226 release that should be available from the update page now.

**Comment by rhe-ch** [comment]
works fine after update ( fyi beware of my "workaround"  : the file removal prevented beo-server.js to start )

**Comment by hifiberry** [comment]
Thanks for the feedback.
