### ISSUE TITLE
Volume slider not adjustable with Spotify Connect

### ISSUE THREAD

**Issue by hyperbart** [hifiberry/hifiberry-os#431]
First of all let me say how awesome this OS and the design of it is, I was really impressed with the UX and the integration within the B&O system.

However, there is something that makes my eyelids twitch a bit ;)

**Describe the bug**
When playing music via Spotify Connect the volume slider on the web interface is

1. non responsive,
2. is always at 0%,
3. jumps back to 0% when you slide
4. when it works it is not "in sync" with the device, so the sliders operate stateless of each other.

**HiFiBerryOS version**
![image](https://user-images.githubusercontent.com/2131310/224049511-e67eebbf-834e-41c1-96a0-df5a71087672.png)

**HiFiBerry sound card**
![image](https://user-images.githubusercontent.com/2131310/224049455-de64e297-c055-461c-8af4-8fbfcadf4463.png)

**Powersupply**
Meanwell 20V Power Supply 200W

**To Reproduce**
1. Enable Spotify Connect
2. Open Spotify on iPhone
3. Play track and play it via Spotify Connect on the Hifiberry
5. Go to the Webinterface of your Hifiberry
6. Try to manipulate the volume via the web interface
7. See error
8. After some reboots and trying again the volume slider just now started working
9. however the volume is not synced across the devices.

**Expected behavior**

1. Volume slider shows current volume
2. Volume slider can be controlled

**Screenshots**

**Browser (if applicable)**
 - OS: iOS
 - Browser Safari
 - OS: Windows 11
 - Browser Firefox

**Comment by hifiberry** [comment]
Looks like something is broken in your setup as we don't see this here. What sound card are you using?

**Comment by hyperbart** [comment]
It's a fresh install, as in: 2 days old.

![image](https://user-images.githubusercontent.com/2131310/224071163-d7506c37-40ed-40ad-a2ed-50897bb1eb83.png)

**Comment by hyperbart** [comment]
> 

Have you tried syncing the volumes, they don't move with each other, if you change the webplayer volume, the Airplay volume slider does not change. Must be reproducable.

**Comment by hifiberry** [comment]
Works here just fine. Is this a fresh installation?

**Comment by hifiberry** [comment]
Unfortunately I can't reproduce this here. It's just working fine in several installations here.
