### ISSUE TITLE
Pi Zero Spotify support

### ISSUE THREAD

**Issue by mdvthu** [hifiberry/hifiberry-os#442]
**Is your feature request related to a problem? Please describe.**
HifiBerryOS doesn't currently support Spotify on the Pi Zero, even though the Pi Zero hardware is more than capable of running Spotify on other audio-focused less performance optimised operating systems (including VolumIO and moOde audio). HifiBerry on Zero should be technically able to run Spotify, even if not as responsive as it could be.

**Describe the solution you'd like**
An option to enable the Spotify connector on HifiBerryOS. If performance is not as good as you would like, a default disabled policy with instructions on how to enable (+/- disclaimer, if concern about impact on the HifiBerry brand)

This is not out of choice but necessity! Pi Zeros are far easier to buy, in the current market.

**Describe alternatives you've considered**
VolumIO and moOde audio. Both of these are not as good as HifiBerryOS. I really like the heavily optimised buildroot based approach that HifiBerry have taken.

**Comment by hifiberry** [comment]
I'm sorry, but we won't spend any more time on the software for the Pi Zero. You can try to build your own image.

In the future, we'll probably stop providing images for ARM6 platforms at all as this simple adds lots of work on our side.
