### ISSUE TITLE
audiocontrol2 plugin gets deleted on OS update

### ISSUE THREAD

**Issue by borkog** [hifiberry/hifiberry-os#443]
I wrote an ac2 plugin, it gets deleted when I update os. 

Plugin is located in /opt/audiocontrol2/ac2/plugins/control/

Not sure whether to call this a bug... Is there a workaround?

**Comment by LopeKinz** [comment]
its because the os itself replaces alot of files. so your plugin gets deleted due to the change of some files from audiocontrol. so its not a bug

**Comment by hifiberry** [comment]
@LopeKinz is (partially) right. You should not put any plugins in /opt. The only safe file system that will survive an update is /data.

Have a look here:
https://github.com/hifiberry/audiocontrol2/blob/master/doc/extensions.md

**Comment by borkog** [comment]
thanks ... but where do I put

plugin_dir=/data/ac2plugins
metadata=MyDisplay
