### ISSUE TITLE
Does a touchdisplay work trough hdmi and usb?

### ISSUE THREAD

**Issue by LopeKinz** [hifiberry/hifiberry-os#446]
**Is your feature request related to a problem? Please describe.**

nop

**Describe the solution you'd like**

i got a 7" Touch Display from Amazon that works perfectly with the official Raspberry pi os. does it work with hifiberry os?

Output via HDMI
Touch Input via USB

**Describe alternatives you've considered**

**Additional context**
Need it for a School Project lmao

**Comment by hifiberry** [comment]
We can't say. You can try, but the only display tested by us is the official Raspberry Pi touchscreen.
