### ISSUE TITLE
Temperature Check (Debug Menu)

### ISSUE THREAD

**Issue by LopeKinz** [hifiberry/hifiberry-os#447]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
A debug menu for measuring temperatures from Raspberrypi with current fanspeed (if possible)  

**Describe alternatives you've considered**

**Additional context**
For Debugging temps inside a housing to check if additional cooling is needed

**Comment by grischard** [comment]
Until the temperature gets added to the system diagnostics page, It's relatively easy to ssh to the pi and run:

```bash
awk '{printf "%.1f C\n", $1/1000}' /sys/class/thermal/thermal_zone0/temp
57.9 C
```
