### ISSUE TITLE
Radio Playback Issues

### ISSUE THREAD

**Issue by Martyn5005** [hifiberry/hifiberry-os#45]
Hi,

works great, love it brought my aging but fairly good HiFi back to life.

One slight bug, I think, is that using the web interface I start the radio playing (Radio Caroline of course). Then when the phone screen blanks the radio stops playing. The radio is not using blue tooth.

Rebooting while radio playing, restarts the HiFi Berry with the radio playing and will continue to play when phone goes to standby.

Thanks

Martyn

**Comment by hifiberry** [comment]
With "phone screen blanks" you mean when it locks the screen? What phone and web browser are you using?
