### ISSUE TITLE
"Select Listening Mode" Interact Action not working with Source Started trigger, due to code bug.

### ISSUE THREAD

**Issue by onnoj** [hifiberry/hifiberry-os#454]
**Describe the bug**
The "Select Listening Mode" action does not work in combination with the Source Started trigger. The action is not executed.

**HiFiBerryOS version**
20230404 / Beocreate 2.4.5

**HiFiBerry sound card**
DAC+ DSP

**To Reproduce**
1. Go to 'Interact'
2. Make sure Interactions are enabled.
3. Click "New Interaction"
4. Configure trigger "Source Started" (for example, with Any Source)
5. Configure action "Select Listening Mode"
6. Select a listening mode (can be default or custom).

**Expected behavior**
When a source starts playing, it is expected that the system will change the listening mode to the configured value.
However, it is observed that the listening mode currently remains unchanged.

**Additional context**
This is caused by a bug in the code of the Beosonic extension: https://github.com/hifiberry/create/blob/44cea31dbc2ab32598fef7bea76d44784a3db816/Beocreate2/beo-extensions/beosonic/index.js#L527

Here, we arrive at the else branch after testing !interactData.preset, but, the subsequent code does not use interactData.preset. Instead it uses triggerResult (same as the logic for when there is no preset in the interactData). The code may have been copy/pasted erroneously.
```
if (!interactData.preset) {
   /* snip */
} else {
	if (compactPresetList[triggerResult]) {
		applyBeosonicPreset(triggerResult);
		return compactPresetList[triggerResult].presetName;
	} else {
		return undefined;
	}
}
```
A fix could be:
```
if (!interactData.preset) {
	/* snip */
} else {
	if (compactPresetList[interactData.preset]) {
		applyBeosonicPreset(interactData.preset);
		return compactPresetList[interactData.preset].presetName;
	} else {
		return undefined;
	}
}
```

I can provide a PR, but, please let me know if you want that in [hifiberry](https://github.com/hifiberry)/[create](https://github.com/hifiberry/create) or in the [bang-olufsen](https://github.com/bang-olufsen)/[create](https://github.com/bang-olufsen/create) repo, I wasn't sure as the latter hasn't been touched in 2 years. Or if you maybe just want to apply the fix yourself directly. I tested it and it works on my hifiberry :P

**Comment by hifiberry** [comment]
Please provide a PR to hifiberry/create
