### ISSUE TITLE
Wrong board detected

### ISSUE THREAD

**Issue by chazman88** [hifiberry/hifiberry-os#457]
**Describe the bug**
Wrong board detected.
HifiBerryOS has detected "DAC+ Zero/Light/MiniAmp"
Board installed is "HiFi Berry Digital-Pro HW 1.2"

/boot/config.txt currently has "dtoverlay=hifiberry-dac"

according to the board it should be "dtoverlay=hifiberry-digi"

**HiFiBerryOS version**
20230404

**HiFiBerry sound card**
HiFi Berry Digital-Pro HW 1.2

<img width="602" alt="Screenshot 2023-05-10 at 14 55 27" src="https://github.com/hifiberry/hifiberry-os/assets/8913039/5fb80602-1ed7-4840-971a-b2b59073312e">

![IMG_3158](https://github.com/hifiberry/hifiberry-os/assets/8913039/ac963f8c-40ff-4a83-92ec-2c7fb52ee196)

**Comment by hifiberry** [comment]
This board is not compatible with the Pi 4 HW 1.5. You need the latest Digi2 Pro for this Pi version.

**Comment by chazman88** [comment]
Dammit!
Is there a Pi board that will work with this HifiBerry board and HifiBerryOS?

**Comment by chazman88** [comment]
@hifiberry Or maybe a discount code to make having to replace my existing board a little less painful??

**Comment by hifiberry** [comment]
All Pi2/3 will work fine.
