### ISSUE TITLE
Invalid environment assignment, ignoring: /data/ac2plugins:/etc/audiocontrol2

### ISSUE THREAD

**Issue by qerub** [hifiberry/hifiberry-os#46]
Looking in the system journal I see this error:

```
/usr/lib/systemd/system/audiocontrol2.service:8: Invalid environment assignment, ignoring: /data/ac2plugins:/etc/audiocontrol2
```

It's caused by [this line](https://github.com/hifiberry/hifiberry-os/blob/dccd5a144a0c79646fbac1a9fad5b6d3b0a48d95/buildroot/package/audiocontrol2/audiocontrol2.service#L9):

```
Environment=/data/ac2plugins:/etc/audiocontrol2
```

I'm not sure what the proper value is.

**Comment by hifiberry** [comment]
Fixed with e07dac3c9fea2f299cef54d2e5fcc5552888623f
