### ISSUE TITLE
Upgrade shairport sync to latest

### ISSUE THREAD

**Issue by jludvig** [hifiberry/hifiberry-os#461]
**Is your feature request related to a problem? Please describe.**
I'm having some issues with short dropouts when using airplay from my phone. Also the volume fade on stop is a produces audible clicks. Looking at the release notes for the latest shairport-sync it sounds like they have addressed some network bugs that could resolve my issues.

**Describe the solution you'd like**
Upgrade to shairport-sync 4.2 or later

**Describe alternatives you've considered**
Switching to Volumio, but losing the DSP on my hifiberry dac dsp
Switching to Roon and having to pay another subscription
Using spotify connect at the cost of audio quality

**Additional context**

**Comment by hifiberry** [comment]
We're using an updates shairport-sync on HiFiBerryOS64.
