### ISSUE TITLE
no cover art with ogg files

### ISSUE THREAD

**Issue by kcsys** [hifiberry/hifiberry-os#467]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete feature requests will be closed.
You should remove this comment before posting the feature request.

**Is your feature request related to a problem? Please describe.**
HBOS does not extract metadata cover art from ogg files.

**Describe the solution you'd like**
I would like to see extracted cover art for ogg files, the same as other file formats.

**Describe alternatives you've considered**
folder.jpg method.

**Additional context**
RPi 3B+, AMP3, HBOS 20230404.
Tried to upload screenshots, but no luck ('we can't process that file').

**Comment by hifiberry** [comment]
Thank you for the request. There are no short term plans for this as we see very few people using OGG. However, we're open to pull requests if somebody wants to implement this.
