### ISSUE TITLE
HifiBerryOS for x86 or AMD64.

### ISSUE THREAD

**Issue by ranomier** [hifiberry/hifiberry-os#471]
**Is your feature request related to a problem? Please describe.**
I have a NAS at home that is already running (proxmox), it would be awesome to be able to run HifiBerryOS on x86 or AMD64.
Proxmox allows me to pass devices into this VM, like a BT dongle and a sound card.

**Describe the solution you'd like**
Create a image for x86 or AMD64

**Describe alternatives you've considered**
I tried to find alternatives to HifiBerryOS, the only one that does PC is volumio, but it requires a monthly subscription for basic stuff.

**Additional context**
You guys are awesome! :heart:

**Comment by hifiberry** [comment]
Sorry, but this won't happen. HiFiBerryOS is tidly integrated with HiFiBerry sound cards. It is not a general-purpose-music player.
