### ISSUE TITLE
Support for mixing SPDIF with other sources

### ISSUE THREAD

**Issue by jimipj** [hifiberry/hifiberry-os#477]
**Is your feature request related to a problem? Please describe.**
I want to listen to music while gaming with audio from both sources coming through a single set of speakers.
Currently, doing this requires a custom DSP profile.

**Describe the solution you'd like**
Support added for mixing SPDIF with other sources, along with a toggle included under SPDIF settings.

**Describe alternatives you've considered**
I previously customized the default DSP profile to do this, albeit without a toggle option.
However, I think such a feature should be available by default.

**Additional context**
My attempt to implement this:
![mix](https://github.com/hifiberry/hifiberry-os/assets/62407948/13b2ac19-34ac-4ee6-98ff-7165dc636baf)

I cannot test it until I get my unit back from warranty.
I'm willing to help with a PR for this.

**Comment by hifiberry** [comment]
Feel free to create a PR based on the latest DSP profiles. Please make sure to update the DSP profiles for all Beocreate and DAC+DSP and that this is only available for these (it isn't possible to implement it on the DSP add-on).

Use HiFiBerryOS64 (development branch) as the base for changes.
