### ISSUE TITLE
Current version of librespot used doesn't implement rfc4034 (fixed upstream though)

### ISSUE THREAD

**Issue by arrelid** [hifiberry/hifiberry-os#481]
**Describe the bug**
Using `journalctl -f`, I see a _lot_ of entries like

```
Nov 04 11:00:32 kitchen vollibrespot[3866]: [Vollibrespot] : couldn't parse packet from 192.168.110.1:5353: type 47 is invalid
Nov 04 11:00:43 kitchen vollibrespot[3866]: [Vollibrespot] : couldn't parse packet from 192.168.110.1:5353: type 47 is invalid
Nov 04 11:00:45 kitchen vollibrespot[3866]: [Vollibrespot] : couldn't parse packet from 192.168.110.1:5353: type 47 is invalid
Nov 04 11:00:52 kitchen vollibrespot[3866]: [Vollibrespot] : couldn't parse packet from 192.168.110.1:5353: type 47 is invalid
Nov 04 11:01:02 kitchen vollibrespot[3866]: [Vollibrespot] : couldn't parse packet from 192.168.110.1:5353: type 47 is invalid 
```

It looks like this might have been fixed upstream in May, 2022:
https://github.com/librespot-org/libmdns/commit/ca9b28946a111872a63e16a1cc306fd9492cad44

It looks like HiFiBerryOS/main is using a version that doesn't contain that fix - [vollibrespot.mk](https://github.com/hifiberry/hifiberry-os/tree/master/buildroot/package/vollibrespot/vollibrespot.mk) indicates that it's using:
https://github.com/hifiberry/Vollibrespot/commit/5d0aa600d4af3d808a51e56df2bc6d7ee953a494

I'd assume that this would be fixed be upgrading to a newer / the latest version of librespot.

**HiFiBerryOS version**
20230404

**HiFiBerry sound card**
Amp2

**To Reproduce**
Unsure if it's my network environment (other IoT devices, router, others) causing this. But other people have seen this too:
https://github.com/librespot-org/libmdns/issues/19

**Expected behavior**
N/A

**Screenshots**
N/A

**Browser (if applicable)**
N/A

**Additional context**
N/A

**Comment by hifiberry** [comment]
As we can't maintain our own version of volibrespot, we can't change this.
