### ISSUE TITLE
HifiBerryOS 64 - Optical In / Auto-Stop other sources always ON

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/hifiberry-os#491]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
When Optical In Auto-Stop other sources is turned off, it stills behaves like if it was ON

**HiFiBerryOS version**
20231219

**HiFiBerry sound card**
DAC + DSP

**To Reproduce**

**Expected behavior**
I'm expecting Optical In not to Auto-stop others sources when playing.

**Screenshots**

**Browser (if applicable)**

**Additional context**

**Comment by hifiberry** [comment]
I just check this. While TOSLink mutes other sources, it does not stop them. With the DSP profile we supply, TOSLink input always takes precedence over sources on the Pi.
So, if you don't want to have your sources interrupted by TOSLink, you have to disable it.

**Comment by mbolo01** [comment]
So this a change from previous profile that unfortunately does not suit my setup anymore.
My TV is TOSLink connected to the DAC+DSP and I like being able to watch TV while listening to another source. With current profile TV Sound is not muting the other sources unless I paused them.  With your new one it is no longer the case. I'll have to find a other solution for that then.
________________________________
De : HiFiBerry ***@***.***>
Envoyé : vendredi 19 janvier 2024 12:21
À : hifiberry/hifiberry-os ***@***.***>
Cc : mbolo01 ***@***.***>; Author ***@***.***>
Objet : Re: [hifiberry/hifiberry-os] HifiBerryOS 64 - Optical In / Auto-Stop other sources always ON (Issue #491)


I just check this. While TOSLink mutes other sources, it does not stop them. With the DSP profile we supply, TOSLink input always takes precedence over sources on the Pi.
So, if you don't want to have your sources interrupted by TOSLink, you have to disable it.
