### ISSUE TITLE
HifiBerryOS 64 - Could not find a way to apply Room Compensation results

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/hifiberry-os#492]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
After running Room Compensation, I din't find a way to apply the saved results in the Sound Design. USE THIS PRESET is not exposed while opening a preset.

NOTE: I cannot import a saved listening mode either, which I think is related to the above issue

**HiFiBerryOS version**
20231219

**HiFiBerry sound card**
DAC+DSP

**To Reproduce**

**Expected behavior**
Being able to apply the results of the Room Compensation analysis in the Sound Design

**Screenshots**

**Browser (if applicable)**

**Additional context**

**Comment by hifiberry** [comment]
You applay the room equalization directly in the "Room equalisation" screen. Just check, it's working fine.

**Comment by hifiberry** [comment]
Switching listening modes also works here. Please attach a full way how to reproduce the issue with screen shots. 

You just have to click on the Room EQ in the Room equalisation screen to apply it. There is no "Apply" button.

**Comment by mbolo01** [comment]
This is what I have in the Room Compensation screen and when I click on the one I have recorded. Does it mean that the only one I have is selected by default ?

I'll send screenshots for the listening mode when I can get the control on the PI back, not sure why it is requesting two DHCP adresses while I think I disabled the WiFi in it.

________________________________
De : HiFiBerry ***@***.***>
Envoyé : vendredi 19 janvier 2024 12:25
À : hifiberry/hifiberry-os ***@***.***>
Cc : mbolo01 ***@***.***>; Author ***@***.***>
Objet : Re: [hifiberry/hifiberry-os] HifiBerryOS 64 - Could not find a way to apply Room Compensation results (Issue #492)


Switching listening modes also works here. Please attach a full way how to reproduce the issue with screen shots.

You just have to click on the Room EQ in the Room equalisation screen to apply it. There is no "Apply" button.

**Comment by hifiberry** [comment]
I don't think replying by email with attachments does work. You should reply directly in Github.

**Comment by mbolo01** [comment]
<img width="979" alt="Capture d’écran 2024-01-19 à 12 37 12" src="https://github.com/hifiberry/hifiberry-os/assets/57586871/05654c6b-4c6b-427b-b33e-44188ea2f254">
<img width="1275" alt="Capture d’écran 2024-01-19 à 12 37 04" src="https://github.com/hifiberry/hifiberry-os/assets/57586871/2eb30841-f0fa-450d-898e-192dc43e4bbf">
Here are the Room Compensation screen I have:

**Comment by hifiberry** [comment]
You have to click on "New room compensation" to calculate the compensation.

**Comment by mbolo01** [comment]
Okay ... my fault. Was confused by the "New" term and I didn't remember the only one I did months ago. Sorry for that

**Comment by hifiberry** [comment]
Ok, we might change the naming of the button.

**Comment by mbolo01** [comment]
Also, I can use a saved sound design too. I think I was confused too by the screen sequence, clear to me now.
