### ISSUE TITLE
Docker image/container no longer present after HBOS software update

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/hifiberry-os#506]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
Docker images and containers are removed post software updates

**HiFiBerryOS version**
You find this on the "About" screen. It looks like Software 20YYMMDD
20240124 (64 bits)
**HiFiBerry sound card**
Post the exact type, e.g. DAC+ Pro instead of "DAC+".
DAC+DSP
**To Reproduce**
Update HBOS
Check if previously installed docker image is still here
Attempt to start previously running docker image

**Expected behavior**
Based on your previous recommendations, I thought the way to preserve any particular setup between software updates was to use docker which is not really the case.

**Screenshots**

**Browser (if applicable)**

**Additional context**

**Comment by hifiberry** [comment]
How exactly did you create the container?

**Comment by mbolo01** [comment]
based on a docker-compose.yaml file located in a subfolder of /data/docker

**Comment by hifiberry** [comment]
Ok, I need to check. Can you post the file?

**Comment by mbolo01** [comment]
# cat docker-compose.yaml
version: '3'
services:
  plexamp:
   container_name: plexamp
   privileged: true
   network_mode: "host"
   image: ghcr.io/pmdroid/plexamp-headless-docker:arm64-483
   volumes:
    - /data/docker/plexamp/:/home/plexamp:rw
    - /run:/run:rw
   environment:
    - RELEASE_CHANNEL=version-beta
   restart: unless-stopped

**Comment by mbolo01** [comment]
"Out of the box", the plexamp extension does not work. What is the original GitHub code you relied on ? During the very first Plexamp installation there is a step that requires to input a token pulled from the Plex.tv web site. Some developers have tried to automate it, some didn't. Also, how the installation identifies that I'm running HBOS 64 ARM to pull the right code ?

**Comment by mbolo01** [comment]
Update: I managed to make it work as an extension, I will update https://github.com/hifiberry/extension_plexamp with my findings
