### ISSUE TITLE
HiFiBerryOs 64 - Alpha - Wireless remote control does not work

### ISSUE THREAD

**Issue by burkhre2** [hifiberry/hifiberry-os#509]
The wireless remote control does not work. The USB stick for the remote is recognised (I see the entries with journalctl -f), but the system does not react on any keypress.  When I plug the USB adapter of the wireless remote in a windows computer the remote works in windows, so the remote is ok.
I also tried switching the remote between mouse and keyboard mode, but no effect.

**HiFiBerryOS version**
20240124 (OS 64 Alpha 4)

**HiFiBerry sound card**
DAC+/Amp2

**To Reproduce**
1. Plug in the USB adapter for the remote control
2. Reboot Hifiberry
3. When system is up again press the volume up or volume down keys on the remote 
**Expected behavior**
The volume of the music should change and the volume controller on the webpage should move. But nothing happens.

**Additional context**
Raspberry PI 4 Model B Rev. 1.5

**Comment by hifiberry** [comment]
Fixed in https://github.com/hifiberry/hifiberry-os/commit/f62e28918b0f1fd9105fca0a8b2cf90b28c9e5a6

This will be included in the next Alpha release
