### ISSUE TITLE
RPi Zero W & WaveShare WM8960 audio Hat

### ISSUE THREAD

**Issue by arut16** [hifiberry/hifiberry-os#510]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Hi HiFiBerry team,

I’m planning to install your soft on my RPi Zero W and i want to use a WaveShare WM8960 audio Hat for audio output on a DIY project. Is it compatible ?

Thanks !

**Describe alternatives you've considered**
no considered alternatives.

**Comment by hifiberry** [comment]
No, HiFiBerryOS only supports HiFiBerry sound cards.
