### ISSUE TITLE
HBOS64: DAC+ DSP EQ not working on analog outputs

### ISSUE THREAD

**Issue by jdyanine** [hifiberry/hifiberry-os#512]
I have successfully implemented a Parametric EQ for room correction over the SPDIF output using the "Sound/Parametric Equalizer/Speaker Equalizer" module, and it works great. However, I encountered an issue where the same module, along with "Sound/Channels," is malfunctioning and incapable of adjusting the analog outputs. Although the features are present, they do not function over the analog outputs. It's as if the analog outputs were a pass-through signal.

However, the Sound Design module does modify the analog output. Because it applies filters globally, it is not suitable for equalizing analog outputs separately. Therefore, it does not serve as the subwoofer crossover I am looking for.

I'm using HiFiBerryOS 64 version 20240115, along with the DAC+ DSP hat. Additionally, the Update module is not functional, and I am unable to update to version 20240124 either through the webUI or SSH. I have no clue on how to do it manually.

![DAC-DSP_02-02-2024](https://github.com/hifiberry/hifiberry-os/assets/44032936/98c52b58-c1ca-4d60-9975-514bd7a657dd)

**Comment by jdyanine** [comment]
Since I couldn't update, I flashed the sdcard again to Hifimeberry OS 64 v20240124. The issue of being unable to equalize the analog outputs persists: Outputs A and B are optical, while C and D are analog, and it's not possible to modify signals C and D.

**Comment by hifiberry** [comment]
I can't reproduce this here. Did you install the latest DAC+DSP Profile v15?

**Comment by jdyanine** [comment]
Thank you for your reply. Yes, I'm using v15.

**Comment by jdyanine** [comment]
Even if I mute the C and D channels, the analog outputs still play without
any change. I have no control over the analog outputs, only the volume and
the global EQ inside 'Sound Design.'

Thank you!

**Comment by hifiberry** [comment]
I can't reproduce it here. Try re-installing the DSP profile

**Comment by jdyanine** [comment]
I didn't notice any change after updating and reinstalling the DSP profile.

I've come to realize that the HifiBerry DAC+ DSP only has two channels,
rendering Channels C and D useless. I'm only able to control Channels A and
B, which affect both the optical and RCA outputs.

Therefore, it's not possible to use it as a subwoofer crossover for a 2.1
setup.

**Comment by hifiberry** [comment]
That's the expected behavior. To change this, you need to create your own DSP profile.
