### ISSUE TITLE
DAC+DSP optical input only works with Spotify Connect at same time

### ISSUE THREAD

**Issue by FatToni** [hifiberry/hifiberry-os#513]
**Describe the bug**
The optical input signal is detected and can be recogniced at the UI with "Playing" indicator but will not output sound independetly.
The optical Toslink input is only working if i start/let run some musik with Spotify Connect. 
As soon I pause/stop the Spotify Connect musik the optical input sound will stop playing. 
I can only use the optical input if the spotify connect is playing some music in the background.

**HiFiBerry Version 20230404**
I tryed different DPS Versions from 11 to 15. Currently Version 15 is working with this Spotify Connect Bug.

**HiFiBerry DAC+DSP**
with Rapberry pi3 

**To Reproduce**
1. Start Spotify @ iphone and play musik with Spotify Connect 
2. Start optical input signal
3. Sound output will switch from Spotify to optical source
4. Sound from spotify is not hearable
5. Pause / stop spotify music, the optical input sound will also stop after a few seconds.  

**Expected behavior**
Fix the bug to use optical input independently
Thanks for your effort

**Screenshots**

**Browser (if applicable)**

**Additional context**
![HiFi2 Toslink OK 1](https://github.com/hifiberry/hifiberry-os/assets/447377/465b69ae-0512-41ac-9344-f9df9d38f316)
![HiFi2 Toslink OK](https://github.com/hifiberry/hifiberry-os/assets/447377/b7fd1250-1aaf-46ee-b718-c8deb0dde8c5)

**Comment by hifiberry** [comment]
Do I understand you correctly: v15 is working?

**Comment by FatToni** [comment]
V15 is the only version i get music with the optical input, but I need to use the spotify play trick in the backround. If spotify is stopped the optical input sound will also stop.

**Comment by FatToni** [comment]
Problem Solved. I reset everything with clear OS installation and DSP Version 15. Now optical is working as it should.
