### ISSUE TITLE
Web App on iOS 17.4

### ISSUE THREAD

**Issue by moritzmhmk** [hifiberry/hifiberry-os#515]
**Describe the bug**
Web Apps will not work with iOS 17.4 - please consider filling the form provided by https://open-web-advocacy.org/blog/its-official-apple-kills-web-apps-in-the-eu/ as a company effected by the change.

**HiFiBerryOS version**
Any

**HiFiBerry sound card**
Any

**To Reproduce**
Try to add Web App to Homescreen in iOS 17.4

**Expected behavior**
App added to Homescreen working as a standalone Web App.

**Screenshots**
Not applicable.

**Comment by hifiberry** [comment]
While we can fill out this, there's nothing else we can do about. As I'm not based in the EU, I can't even test this.

**Comment by sebastianrothe** [comment]
Apple returns to being reasonable: https://open-web-advocacy.org/blog/apple-backs-off-killing-web-apps/
