### ISSUE TITLE
HBOS 64 - Create New Backup not working

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/hifiberry-os#516]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
When trying to "Create New Backup" , nothing happens but "Archiving settings, please wait..." and spinning wheel continuously 

**HiFiBerryOS version**
20240124

**HiFiBerry sound card**
DAC+DSP

**To Reproduce**
1. Go to 'General/ System Tools'
2. Click on 'Create New Backup'
4. See error "Archiving settings, please wait..." for ever

**Expected behavior**
Backup Files saved in download area defined by browser settings

**Screenshots**

**Browser (if applicable)**
 - OS: MACOS Sonoma 14.2.1
 - Browser Safari 17.2.1 and Barave 1.62.165

**Additional context**
Note: Despite no popup to authorize download site (HBOS URL), it has been manually authorized to download to see it it makes a difference, unsuccessfully

**Comment by hifiberry** [comment]
Fixed with patch d7d759a9014e9a93fc1ec51900642d5ba62b7b11

**Comment by hifiberry** [comment]
https://github.com/hifiberry/hifiberry-os/commit/d7d759a9014e9a93fc1ec51900642d5ba62b7b11
