### ISSUE TITLE
RAAT Service not startable on RPI4 with DIGI+ Pro

### ISSUE THREAD

**Issue by mvonrotz** [hifiberry/hifiberry-os#524]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
I am not able to start the service for RAAT, neither by the web page nor the console. On the web page in sources/net

**HiFiBerryOS version**
20230404
**HiFiBerry sound card**
"DIGI+ Pro" but it shows "DIGI+ Pro + DSP Module" - I do not have a DSP Module connected

**To Reproduce**
1. Go to 'SOURCES'
2. Click on 'Disabled Sources....'
3. Click on "Roon"
4. Select "On"
5. Wait for starting display to finish
6. go back to "SOURCES"
7. Roon appears shortly and disappears again and is disabled again

**Expected behavior**
Roon to be shown in the enabled sources list

**Screenshots**

**Browser (if applicable)**
 - OS: [Windows 10]
 - Browser [chrome,]
 - Version [122.0.6261.131]

**Additional context**
Output of systemctl status raat

raat.service - Roon
     Loaded: loaded (/usr/lib/systemd/system/raat.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-03-20 16:54:57 CET; 1s ago
    Process: 12490 ExecStartPre=/opt/hifiberry/bin/bootmsg Starting Roon (code=exited, status=0/SUCCESS)
    Process: 12494 ExecStartPre=/opt/hifiberry/bin/pause-all raat (code=exited, status=1/FAILURE)
    Process: 12639 ExecStart=/opt/raat/raat_app /etc/hifiberry_raat.conf (code=exited, status=1/FAILURE)
   Main PID: 12639 (code=exited, status=1/FAILURE)

**Comment by hifiberry** [comment]
Looks like some problem with the detection of your Digi+. Please try the latest HifiBerryOS64 Alpha:
https://github.com/hifiberry/hifiberry-os/releases/tag/64alpha6

**Comment by mvonrotz** [comment]
Thanks, but this did not solve the problem. The behaviour is the same. What I forgot to write in the inital issue submission is that without a "noreboot" file in the root directory, the PI remains in a reboot loop.

What I will test now is to start the PI without the Hifiberry board and see what the result is.

**Comment by hifiberry** [comment]
You're probably using an old Digi+ Pro on the latest Pi4. These are not compatible:
https://www.hifiberry.com/blog/digi2-pro-raspberry-pi-4-1-5-incompatibilities/

**Comment by mvonrotz** [comment]
Funny thing - obviously starting the PI without the HAT was of no use. I reassembled the device and startet it again, and oh wonder, Roon (RAAT) is running :-)

**Comment by mvonrotz** [comment]
Aah - after the next reboot the problem was back again :-( - And now even the GUI is not starting anymore :-(
will reflash again and see, but no big hope :-)

**Comment by hifiberry** [comment]
If your Digi+ isn't compatible with your Pi4, there is nothing you can do in software.

**Comment by mvonrotz** [comment]
Ok, that is bad luck on my side to get an "old" revision of the hardware. Have ordered a new one already :-). Thanks for the support!!
