### ISSUE TITLE
HifiBerryOS64 Alpha 7: Now playing in statusbar not showing spotify daemon 

### ISSUE THREAD

**Issue by baldrianbandit** [hifiberry/hifiberry-os#535]
**Describe the bug**
Now playing information in statusbar not shown for spotify daemon

**HiFiBerryOS version**
HifiBerryOS64 / Alpha 7

**To Reproduce**
1. Start spotify daemon
2. Play some title via spotify daemon
3. Statusbar not showing info

**Comment by hifiberry** [comment]
Did you enable metadata for the player?

**Comment by baldrianbandit** [comment]
Cannot, since use_mpris=true results in spotify daemon dbus error.

**Comment by hifiberry** [comment]
In this case, that's just the normal behavior.
