### ISSUE TITLE
Hifiberry 64Bit Alpha UI doesn’t work with SocketIO enabled

### ISSUE THREAD

**Issue by Guy559** [hifiberry/hifiberry-os#537]
HiFiBerry 64Bit Alpha web UI doesn’t work when SocketIO is enabled.

20240124 alpha release

AMP2

To reproduce, enable SocketIO then reboot. Web UI is no longer accessible, though HiFiBerryOS is now discoverable/controllable via Home Assistant, for example.

 - OS: MacOS (latest) / iPadOS
 - Browser: Safari

**Comment by hifiberry** [comment]
Use the latest version.
