### ISSUE TITLE
Access to hifiberry.local fails due to incorrect TLS setting

### ISSUE THREAD

**Issue by kaskelotti** [hifiberry/hifiberry-os#541]
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
Setting up Hifiberry OS through wifi fails since the address hifiberry.local cannot be accessed with a browser. At least Firefox prevents access to sites where TLS version is older than 1.2.

This issue occurs also when initial setup is done and regular connection to device via network is attempted.

**HiFiBerryOS version**
Image file: hifiberryos-20230404-pi3

**HiFiBerry sound card**
N/A

**To Reproduce**
1. Flash the SD card
2. Boot up
3. Connect to wifi access point per these instructions https://www.hifiberry.com/docs/hifiberryos/hifiberryos-configure-wifi/
4. Go to address hifiberry.local
5. See error that prevents access. On Firefox it's 

```
Secure Connection Failed

An error occurred during a connection to hifiberry.local. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Expected behavior**
Expected the access to be granted.

**Browser (if applicable)**
 - OS: MacOS Monterey 12.7.4
 - Browser Firefox 121.0 (64-bit)

**Comment by hifiberry** [comment]
There is no TLS at all. Web interface traffic is not encrypted at all. As the host doesn't have a unique public host name, not encryption with certificate validation can be used.

**Comment by hifiberry** [comment]
you need to use http://hifiberry.local and check that your system can resolve hifiberry.local. Otherwise, use the IP address instead of hifiberry.local

**Comment by kaskelotti** [comment]
Thanks for the prompt reply!

I see. I can access with IP address on any browser. On first boot hifiberry.local worked with Safari, but with FF I got the error mentioned above.

Maybe this was an user error and misunderstanding on my part. I'll report again if this comes up.
