### ISSUE TITLE
HBOS 64 Alpha 8: Python "No module named 'RPi'"

### ISSUE THREAD

**Issue by kontaktwackler** [hifiberry/hifiberry-os#555]
**Describe the bug**
I am trying to reuse a python script used to control volume via a rotary encoder. Script was working fine on latest non 64bit hifiberry os version. on 64 alpha 8 the script is not working because this python import command in the script fails:
from RPi import GPIO

**HiFiBerryOS version**
20240523

**HiFiBerry sound card**
DAC+/Amp2

**To Reproduce**
python3: try to import "from RPi import GPIO"

**Expected behavior**
module RPi should be available to be able to control GPIO

**Comment by hifiberry** [comment]
You're right. However as the GPIO module uses an old kernel interface that's not available anymore, we can't add this. The code needs to be rewritten.

**Comment by hifiberry** [comment]
I just noticed that you're using your own script. In this case, you have to rewrite it. Rpi.GPIO isn't supported anymore on the latest Linux kernel.

**Comment by kontaktwackler** [comment]
Thanks for the quick reply. Will check how to rewrite for new kernel.

**Comment by hifiberry** [comment]
Have a look at the gpiod module, e.g. here:
https://github.com/hifiberry/audiocontrol2/blob/master/ac2/plugins/control/powercontroller.py
