### ISSUE TITLE
User-facing documentation?

### ISSUE THREAD

**Issue by bam80** [hifiberry/hifiberry-os#557]
Hi,
it's not clear how to get started: install/configure, etc.

Did I miss the documentation?

**Comment by innir** [comment]
You might look for https://www.hifiberry.com/hifiberryos

**Comment by bam80** [comment]
Thanks, found it myself already.
Probably worth make it more explorable from the Readme.

**Comment by bam80** [comment]
>  Probably worth make it more explorable from the Readme.

IIRC, it wasn't addressed yet?
