### ISSUE TITLE
Readme: Clarify Services

### ISSUE THREAD

**Issue by bam80** [hifiberry/hifiberry-os#558]
At the first glance, it's not clear what some Services are about.
For example, "Bluetooth" might mean input and/or output:
https://github.com/hifiberry/hifiberry-os/blob/16325cf6992ee0a0693c262a6270f4f2e6377426/README.md?plain=1#L17-L30

**Comment by hifiberry** [comment]
Thanks for this. Feel free to edit the file and send an update. You can just edit the file on Github.

**Comment by bam80** [comment]
Could we keep it open until it's not done, please?
