### ISSUE TITLE
hifiberryos-alpha8.zip attached display not working

### ISSUE THREAD

**Issue by pdavies91** [hifiberry/hifiberry-os#565]
**Describe the bug**
Raspberry pi 3b+
Running originally the 20230404, works fine (with some niggles). 
Installed hifiberryos-alpha8.zip onto another card inserted and started.
Rainbow screen comes and goes.... then rotates through white, green, red .....screens 

**HiFiBerryOS version**
hifiberryos-alpha8.zip

**HiFiBerry sound card**
DAC+/Amp2

**To Reproduce**
1. INstall SD card and power up

**Expected behavior**
Should display HifiberrOS interface

**Comment by user10072023github** [comment]
Seems to be a common theme...I'd stay on the old version if that's working ok for ya.  Wish the team would get back to folks.

**Comment by hifiberry** [comment]
See https://github.com/hifiberry/hifiberry-os/issues/560

**Comment by pdavies91** [comment]
Moved to Moode Audio
