### ISSUE TITLE
Build for Pi Zero 2 "02" fails for Alpha8

### ISSUE THREAD

**Issue by stefanheinrichsen** [hifiberry/hifiberry-os#568]
**Describe the bug**
When I try to compile for a Pi Zero 2 I get a error which I don't know to handle.

**HiFiBerryOS version**
HifiBerry OS 64 Alpha 8 (downloaded the tarball)

**HiFiBerry sound card**
Not applicable as I'm building the image

**To Reproduce**

1. ./prepare-software as root
2. Download tarball and extract
3. rename extracted folder to "hifiberry-os"
4. cd into it
5. ./build-config 02
6. ./config (I did not change anything)
7. ./compile 02
8. (Wait for 60-90 Minutes)
9. compile stopps with error

**Expected behavior**
I would expect the compile process works.

**Screenshots**
The error which is shown is:
```
GIT_DIR=. PATH="/home/stefan/hifi/buildroot-02/host/bin:/home/stefan/hifi/buildroot-02/host/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games" PKG_CONFIG="/home/stefan/hifi/buildroot-02/host/bin/pkg-config" PKG_CONFIG_SYSROOT_DIR="/" PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_LIBDIR="/home/stefan/hifi/buildroot-02/host/lib/pkgconfig:/home/stefan/hifi/buildroot-02/host/share/pkgconfig" BR_BINARIES_DIR=/home/stefan/hifi/buildroot-02/images KCFLAGS=-Wno-attribute-alias DTC_FLAGS=-@ /usr/bin/make -j13 HOSTCC="/usr/bin/gcc -O2 -isystem /home/stefan/hifi/buildroot-02/host/include -L/home/stefan/hifi/buildroot-02/host/lib -Wl,-rpath,/home/stefan/hifi/buildroot-02/host/lib" ARCH=arm INSTALL_MOD_PATH=/home/stefan/hifi/buildroot-02/target CROSS_COMPILE="/home/stefan/hifi/buildroot-02/host/bin/arm-buildroot-linux-gnueabihf-" WERROR=0 REGENERATE_PARSERS=1 DEPMOD=/home/stefan/hifi/buildroot-02/host/sbin/depmod INSTALL_MOD_STRIP=1 -C /home/stefan/hifi/buildroot-02/build/linux-custom bcm2710-rpi-zero-2-w.dtb
make[1]: Entering directory '/home/stefan/hifi/buildroot-02/build/linux-custom'
make[3]: *** No rule to make target 'arch/arm/boot/dts/bcm2710-rpi-zero-2-w.dtb'.  Stop.
make[2]: *** [/home/stefan/hifi/buildroot-02/build/linux-custom/Makefile:1384: bcm2710-rpi-zero-2-w.dtb] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
```

**Browser (if applicable)**
n/a

**Additional context**
I'm using a Debian bookworm (12.7) as build system. It has 64 GByte RAM and plenty of free disc space.

I've already searched for "bcm2710-rpi-zero-2-w.dtb" and the file as such exists. Not in the folder "arch/arm/boot/dts/"  but instead in "arch/arm/boot/dts/broadcom". So maybe some path name must be adjusted somewhere?

Any help/hint is welcome.

Best regards,
  Stefan

**Comment by hifiberry** [comment]
There is only a single 64bit build. You need to use "4" for the 64bit build that supports all 64bit models (P3-Pi5, Zero 2)
