### ISSUE TITLE
A new release with Shairport version 4.3.4

### ISSUE THREAD

**Issue by dodepier** [hifiberry/hifiberry-os#580]
**Is your feature request related to a problem? Please describe.**
Would like to use a more stable version of shairport (airplay 2) on my hifiberry's with raspberry 3A+

**Describe the solution you'd like**
- A new release with an updated version of Shairport.

**Describe alternatives you've considered**
- Alternatively, instructions on how to build an image myself with an updated Shairport version.

**Additional context**
hifiberry 20230404 version shairport hifiberry 4.1, last stable version of shairport 4.3.4.

https://github.com/mikebrady/shairport-sync/releases/tag/4.3.4

![image](https://github.com/user-attachments/assets/fc5fa648-0c59-4033-ba9c-fde0d2ad7716)

**Comment by hifiberry** [comment]
We do not plan any updates on the existing HiFiBerryOS, but focus on HBOS64. This comes with a newer version of Shairport sync
