### ISSUE TITLE
Unable to control volume @ optical input on Rasberry4

### ISSUE THREAD

**Issue by chardad** [hifiberry/hifiberry-os#65]
Hi,
I am a user of beocreate4CA and hifiberryOS(20200403). It's a really great music player.  When I use Rasberry3B. Everything is OK.
But when I change to Rasberry4B there are some errors.
- Can't control the main volume @ optical input (I can control volume in volume limit. Other sources are OK.)
- the main volume is less loud then rasberry3.  Rasberry3 is good level @50 but Rasberry4 is good @90
How can I solve these issures?
Thanks in advance!!

**Comment by hifiberry** [comment]
Did you re-install the DSP profile after installing the system on the Pi4?

**Comment by chardad** [comment]
I do down load HifiberryOS image (hifiberryos-20200403-pi4.img) which was used for rasberry3B.
How could I re-install the DSP profile?

**Comment by hifiberry** [comment]
Sound/Advanced/DSP Programs

**Comment by chardad** [comment]
I do re-install in DSP Programs / Beocreate Universal / REINSTALL THIS PROGRAM
then DSP installed and restart.
I can control optical source volume in main volume!!  Thanks!!

But less loud problem then RPI3B is not solved.  How could I make louder?

**Comment by hifiberry** [comment]
Try rebooting now

**Comment by chardad** [comment]
Great!!  I can solve problem after rebooting

Thanks for your great support!
