### ISSUE TITLE
20200330: Update from UI not available.

### ISSUE THREAD

**Issue by lost-carrier** [hifiberry/hifiberry-os#71]
I wanted to do a manual update from the WebUI (in order to keep my settings), but "General" -> "Software Update" shows "No updates are currently available".

I'm on 20200330 - according to GitHub releases page there should be 20200403 and 20200424 available.
![Bildschirmfoto 2020-04-28 um 20 37 13](https://user-images.githubusercontent.com/3090579/80524797-7b96d580-8990-11ea-9071-2d4331887c4e.png)

**Comment by hifiberry** [comment]
This is a bug in the UI. You need to set automatic updates to "quick" or "latest". Otherwise only security updates will be displayed here. This has been fixed in the April version (select "Quick" for this).

**Comment by lost-carrier** [comment]
OK... needed a reboot after changing this, but now it works! Thanks!
