### ISSUE TITLE
Jack output not working

### ISSUE THREAD

**Issue by ced455** [hifiberry/hifiberry-os#81]
Hello, 

I set up hifiberry on a raspberry 4 model B over wifi, the setup went well i can access the webpage and reach the device from spotify airplay, but no output, I use the jack.
Would you know any way i can use to debug / fix the issue ?

thank you

**Comment by hifiberry** [comment]
With "jack" you mean the onboard sound? This won't work at all. Raspberry Pi onboard sound isn't supported. You need a HiFiBerry sound card for HiFiBerryOS.

**Comment by ced455** [comment]
ahhh, i wanted to see if everything was working first, i guess i need to purchase it !
thank you !
