### ISSUE TITLE
websockets are broken when behind a https reverse proxy

### ISSUE THREAD

**Issue by fizzyade** [hifiberry/hifiberry-os#82]
beo-comes.js assumes that the server is running on http, when using a http/2 proxy (I use caddy) it attempts to open a non-secure websocket connection (ws://) which is prohibited as upgrades are not allowed.

The code should be modified to detect whether to use ws:// or wss:// connections.

Currently it does not work, you just get a spinning connecting logo and the javascript console shows the error regarding web sockets.

**Comment by hifiberry** [comment]
As this is a request for the UI, please report it at the UI component:
https://github.com/bang-olufsen/create
