### ISSUE TITLE
Airplay 2 module by Argyropus

### ISSUE THREAD

**Issue by fordsteve** [hifiberry/hifiberry-os#90]
Absolutely loving your work after installing HiFiBerryOS. Is it possible for me to be able to install the Airplay 2 module by Argyropus or is the OS locked for your engineers?
Thanks guys!

**Comment by hifiberry** [comment]
Nothing is locked. You are here at the full sources of HiFiBerryOS. I can't say if you are able to add more software, but it's possible in general. I recommend to study the documentation:
https://github.com/hifiberry/hifiberry-os/tree/master/doc

**Comment by fordsteve** [comment]
Thank you!
