### ISSUE TITLE
DAC+ DSP hat not detected

### ISSUE THREAD

**Issue by Chaz6** [hifiberry/hifiberry-os#91]
After swapping the DAC+ Pro XLR hat for a DAC+ DSP hat I am unable to access the DSP settings through the web interface.
![image](https://user-images.githubusercontent.com/12680/83332664-60233100-a294-11ea-8e00-0f74c6868182.png)

**Comment by Chaz6** [comment]
[hifiberry-debug.zip](https://github.com/hifiberry/hifiberry-os/files/4705939/hifiberry-debug.zip)
Attached hifiberry-debug.zip.

**Comment by hifiberry** [comment]
I recommend to upgrade to the May release first and try again (you need to change updates to "Quick") as this isn't yet marked as the standard release.

**Comment by Chaz6** [comment]
Thanks, working now!
