### ISSUE TITLE
Add balance support

### ISSUE THREAD

**Issue by tinue** [hifiberry/hifiberry-os#92]
In my home office I can't place the loudspeakers equidistant to my desk / chair. It would therefore be great to have support for a "balance" setting, so that I can operate the left speaker at a louder volume. Alsamixer does support this, but I guess I would have to log in via SSH, and I would probably lose the setting after a reboot.
I tried to use "Room Compensation", but apparently it does not measure / compensate for this.

**Comment by hifiberry** [comment]
Balance is available for DSP-enabled sound cards, not for other cards. What are you using?

**Comment by tinue** [comment]
I am using the Amp2.

**Comment by hifiberry** [comment]
There is no integrated balance control on the Amp2. Therefore this would require some ALSA hacking. It's not planned to do this, but if somebody wants to contribute this, we'll look into integrating it.
