### ISSUE TITLE
wrong checksum or pi 4 for 20200527 release

### ISSUE THREAD

**Issue by jgabriel98** [hifiberry/hifiberry-os#95]
After flashing the pi4 .img file from [v20200527](https://github.com/hifiberry/hifiberry-os/releases/tag/v20200527) in a 8gb sd card, the balenaEtcher software pointed that the checksum did not match.

**Comment by hifiberry** [comment]
That's a problem of your SD card. It has nothing to do with the image. You should try a new SD card.
