### ISSUE TITLE
Ability to use Bluetooth USB dongle

### ISSUE THREAD

**Issue by KomtGoed** [hifiberry/hifiberry-os#96]
In order to increase the BT range, it would be good to be able to use a Bluetooth USB dongle, even on a Pi 3B+.

**Comment by hifiberry** [comment]
While this is an interesting use case, it won't be a top priority for us. While we **might** implement this at some point, we can't commit this. However, if you want to implement this and send us a pull-request, we would integrate it.

**Comment by hifiberry** [comment]
This has been implemented in 202008.
