### ISSUE TITLE
Digital passthrough with Digi+ I/O

### ISSUE THREAD

**Issue by odel4y** [hifiberry/hifiberry-os#97]
**Is your feature request related to a problem? Please describe.**
I would like the Hifiberry (Digi+ I/O) to be the primary device on the optical input of my active speaker system. As my TV also has an optical output I would like to be able to switch between the two. 

**Describe the solution you'd like**
Like the analog input option in Hifiberry OS, it would be nice to include a digital input option. With this option, the Hifiberry would just copy the digital input to the digital output.

**Describe alternatives you've considered**
Of course I could also use another input of my speakers for the TV. But I would prefer software control about the source of sound in the Hifiberry.

Thank you for this nice software!

**Comment by hifiberry** [comment]
This is possible with the DAC+ DSP. As the Digi+ I/O won't allow us to detect a signal, it doesn't really fit in well. I don't think we'll implement this by ourselves. However, we're open for contributions.
